// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAabs_INCLUDE_
#define _RAabs_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  RAfloatS fabs(const RAfloatS& a);
  RAfloatD fabs(const RAfloatD& a);
#endif
