// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAabs.hpp"

RAfloatS fabs(const RAfloatS& a) {
  RAfloatS r;
  float factor_0;
  float factor_d;
  #include "RAabs.ipp"
  return r;
}

RAfloatD fabs(const RAfloatD& a) {
  RAfloatD r;
  double factor_0;
  double factor_d;
  #include "RAabs.ipp"
  return r;
}

