// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAacos_INCLUDE_
#define _RAacos_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  #include "RAsqrt.hpp"
  #include "RAdiv.hpp"
  #include "RAmult.hpp"
  #include "RAsub.hpp"
  #include "RAuminus.hpp"
  RAfloatS acos(const RAfloatS& a);
  RAfloatD acos(const RAfloatD& a);
#endif
