// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAasin_INCLUDE_
#define _RAasin_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  #include "RAsqrt.hpp"
  #include "RAdiv.hpp"
  #include "RAmult.hpp"
  #include "RAsub.hpp"
  RAfloatS asin(const RAfloatS& a);
  RAfloatD asin(const RAfloatD& a);
#endif
