// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAasin.hpp"

RAfloatS asin(const RAfloatS& a) {
  RAfloatS r;
  RAfloatS h;
  RAfloatS t;
  #include "RAasin.ipp"
  return r;
}

RAfloatD asin(const RAfloatD& a) {
  RAfloatD r;
  RAfloatD h;
  RAfloatD t;
  #include "RAasin.ipp"
  return r;
}

