// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAatan_INCLUDE_
#define _RAatan_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  #include "RAadd.hpp"
  #include "RAdiv.hpp"
  #include "RAmult.hpp"
  RAfloatS atan(const RAfloatS& a);
  RAfloatD atan(const RAfloatD& a);
#endif
