// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAatan.hpp"

RAfloatS atan(const RAfloatS& a) {
  RAfloatS r;
  RAfloatS y;
  RAfloatS s;
  float one;
  #include "RAatan.ipp"
  return r;
}

RAfloatD atan(const RAfloatD& a) {
  RAfloatD r;
  RAfloatD y;
  RAfloatD s;
  double one;
  #include "RAatan.ipp"
  return r;
}

