// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAcos_INCLUDE_
#define _RAcos_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  RAfloatS cos(const RAfloatS& a);
  RAfloatD cos(const RAfloatD& a);
#endif
