// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAcos.hpp"

RAfloatS cos(const RAfloatS& a) {
  RAfloatS c;
  RAfloatS s;
  RAfloatS t;
  #include "RAsincos.ipp"
  return c;
}

RAfloatD cos(const RAfloatD& a) {
  RAfloatD c;
  RAfloatD s;
  RAfloatD t;
  #include "RAsincos.ipp"
  return c;
}

