// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAcosh.hpp"

RAfloatS cosh(const RAfloatS& a) {
  RAfloatS c;
  RAfloatS s;
  RAfloatS t;
  #include "RAsinhcosh.ipp"
  return c;
}

RAfloatD cosh(const RAfloatD& a) {
  RAfloatD c;
  RAfloatD s;
  RAfloatD t;
  #include "RAsinhcosh.ipp"
  return c;
}

