// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAcosh_INCLUDE_
#define _RAcosh_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  RAfloatS cosh(const RAfloatS& a);
  RAfloatD cosh(const RAfloatD& a);
#endif
