// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAeqadd.hpp"

void operator +=(RAfloatS& r, const RAfloatS& b) {
  #include "RAeqaddAA.ipp"
}

void operator +=(RAfloatD& r, const RAfloatS& b) {
  #include "RAeqaddAA.ipp"
}

void operator +=(RAfloatD& r, const RAfloatD& b) {
  #include "RAeqaddAA.ipp"
}

void operator +=(RAfloatS& r, const int& b) {
  #include "RAeqaddAP.ipp"
}

void operator +=(RAfloatS& r, const float& b) {
  #include "RAeqaddAP.ipp"
}

void operator +=(RAfloatD& r, const int& b) {
  #include "RAeqaddAP.ipp"
}

void operator +=(RAfloatD& r, const float& b) {
  #include "RAeqaddAP.ipp"
}

void operator +=(RAfloatD& r, const double& b) {
  #include "RAeqaddAP.ipp"
}

