// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAeqsub.hpp"

void operator -=(RAfloatS& r, const RAfloatS& b) {
  #include "RAeqsubAA.ipp"
}

void operator -=(RAfloatD& r, const RAfloatS& b) {
  #include "RAeqsubAA.ipp"
}

void operator -=(RAfloatD& r, const RAfloatD& b) {
  #include "RAeqsubAA.ipp"
}

void operator -=(RAfloatS& r, const int& b) {
  #include "RAeqsubAP.ipp"
}

void operator -=(RAfloatS& r, const float& b) {
  #include "RAeqsubAP.ipp"
}

void operator -=(RAfloatD& r, const int& b) {
  #include "RAeqsubAP.ipp"
}

void operator -=(RAfloatD& r, const float& b) {
  #include "RAeqsubAP.ipp"
}

void operator -=(RAfloatD& r, const double& b) {
  #include "RAeqsubAP.ipp"
}

