// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAeqsub_INCLUDE_
#define _RAeqsub_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  void operator -=(RAfloatS& r, const RAfloatS& b);
  void operator -=(RAfloatD& r, const RAfloatS& b);
  void operator -=(RAfloatD& r, const RAfloatD& b);
  void operator -=(RAfloatS& r, const int& b);
  void operator -=(RAfloatS& r, const float& b);
  void operator -=(RAfloatD& r, const int& b);
  void operator -=(RAfloatD& r, const float& b);
  void operator -=(RAfloatD& r, const double& b);
#endif
