// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAeqdiv.hpp"

void operator /=(RAfloatS& r, const RAfloatS& b) {
  RAfloatS a = r;
  float recip;
  #include "RAeqdivAA.ipp"
}

void operator /=(RAfloatD& r, const RAfloatS& b) {
  RAfloatD a = r;
  double recip;
  #include "RAeqdivAA.ipp"
}

void operator /=(RAfloatD& r, const RAfloatD& b) {
  RAfloatD a = r;
  double recip;
  #include "RAeqdivAA.ipp"
}

void operator /=(RAfloatS& r, const int& b) {
  RAfloatS a = r;
  float recip;
  #include "RAeqdivAP.ipp"
}

void operator /=(RAfloatS& r, const float& b) {
  RAfloatS a = r;
  float recip;
  #include "RAeqdivAP.ipp"
}

void operator /=(RAfloatD& r, const int& b) {
  RAfloatD a = r;
  double recip;
  #include "RAeqdivAP.ipp"
}

void operator /=(RAfloatD& r, const float& b) {
  RAfloatD a = r;
  double recip;
  #include "RAeqdivAP.ipp"
}

void operator /=(RAfloatD& r, const double& b) {
  RAfloatD a = r;
  double recip;
  #include "RAeqdivAP.ipp"
}

