// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAeqmult.hpp"

void operator *=(RAfloatS& r, const RAfloatS& b) {
  #include "RAeqmultAA.ipp"
}

void operator *=(RAfloatD& r, const RAfloatS& b) {
  #include "RAeqmultAA.ipp"
}

void operator *=(RAfloatD& r, const RAfloatD& b) {
  #include "RAeqmultAA.ipp"
}

void operator *=(RAfloatS& r, const int& b) {
  #include "RAeqmultAP.ipp"
}

void operator *=(RAfloatS& r, const float& b) {
  #include "RAeqmultAP.ipp"
}

void operator *=(RAfloatD& r, const int& b) {
  #include "RAeqmultAP.ipp"
}

void operator *=(RAfloatD& r, const float& b) {
  #include "RAeqmultAP.ipp"
}

void operator *=(RAfloatD& r, const double& b) {
  #include "RAeqmultAP.ipp"
}

