// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAexp_INCLUDE_
#define _RAexp_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  RAfloatS exp(const RAfloatS& a);
  RAfloatD exp(const RAfloatD& a);
#endif
