// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAle_INCLUDE_
#define _RAle_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  bool operator <=(const RAfloatS& a, const RAfloatS& b);
  bool operator <=(const RAfloatS& a, const RAfloatD& b);
  bool operator <=(const RAfloatD& a, const RAfloatS& b);
  bool operator <=(const RAfloatD& a, const RAfloatD& b);
  bool operator <=(const RAfloatS& a, const int& b);
  bool operator <=(const RAfloatS& a, const float& b);
  bool operator <=(const RAfloatS& a, const double& b);
  bool operator <=(const RAfloatD& a, const int& b);
  bool operator <=(const RAfloatD& a, const float& b);
  bool operator <=(const RAfloatD& a, const double& b);
  bool operator <=(const int& a, const RAfloatS& b);
  bool operator <=(const int& a, const RAfloatD& b);
  bool operator <=(const float& a, const RAfloatS& b);
  bool operator <=(const float& a, const RAfloatD& b);
  bool operator <=(const double& a, const RAfloatS& b);
  bool operator <=(const double& a, const RAfloatD& b);
#endif
