// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAlog.hpp"

RAfloatS log(const RAfloatS& a) {
  RAfloatS r;
  RAfloatS s;
  RAfloatS t;
  float recip;
  #include "RAlog.ipp"
  return r;
}

RAfloatD log(const RAfloatD& a) {
  RAfloatD r;
  RAfloatD s;
  RAfloatD t;
  double recip;
  #include "RAlog.ipp"
  return r;
}

