// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAlog_INCLUDE_
#define _RAlog_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  RAfloatS log(const RAfloatS& a);
  RAfloatD log(const RAfloatD& a);
#endif
