// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAmax_INCLUDE_
#define _RAmax_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  RAfloatS max(const RAfloatS& a, const RAfloatS& b);
  RAfloatD max(const RAfloatS& a, const RAfloatD& b);
  RAfloatD max(const RAfloatD& a, const RAfloatS& b);
  RAfloatD max(const RAfloatD& a, const RAfloatD& b);
  RAfloatS max(const RAfloatS& a, const int& b);
  RAfloatS max(const RAfloatS& a, const float& b);
  RAfloatD max(const RAfloatS& a, const double& b);
  RAfloatD max(const RAfloatD& a, const int& b);
  RAfloatD max(const RAfloatD& a, const float& b);
  RAfloatD max(const RAfloatD& a, const double& b);
  RAfloatS max(const int& a, const RAfloatS& b);
  RAfloatD max(const int& a, const RAfloatD& b);
  RAfloatS max(const float& a, const RAfloatS& b);
  RAfloatD max(const float& a, const RAfloatD& b);
  RAfloatD max(const double& a, const RAfloatS& b);
  RAfloatD max(const double& a, const RAfloatD& b);
#endif
