// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAmin.hpp"

RAfloatS min(const RAfloatS& a, const RAfloatS& b) {
  RAfloatS r;
  #include "RAminAA.ipp"
  return r;
}

RAfloatD min(const RAfloatS& a, const RAfloatD& b) {
  RAfloatD r;
  #include "RAminAA.ipp"
  return r;
}

RAfloatD min(const RAfloatD& a, const RAfloatS& b) {
  RAfloatD r;
  #include "RAminAA.ipp"
  return r;
}

RAfloatD min(const RAfloatD& a, const RAfloatD& b) {
  RAfloatD r;
  #include "RAminAA.ipp"
  return r;
}

RAfloatS min(const RAfloatS& a, const int& b) {
  RAfloatS r;
  #include "RAminAP.ipp"
  return r;
}

RAfloatS min(const RAfloatS& a, const float& b) {
  RAfloatS r;
  #include "RAminAP.ipp"
  return r;
}

RAfloatD min(const RAfloatS& a, const double& b) {
  RAfloatD r;
  #include "RAminAP.ipp"
  return r;
}

RAfloatD min(const RAfloatD& a, const int& b) {
  RAfloatD r;
  #include "RAminAP.ipp"
  return r;
}

RAfloatD min(const RAfloatD& a, const float& b) {
  RAfloatD r;
  #include "RAminAP.ipp"
  return r;
}

RAfloatD min(const RAfloatD& a, const double& b) {
  RAfloatD r;
  #include "RAminAP.ipp"
  return r;
}

RAfloatS min(const int& a, const RAfloatS& b) {
  RAfloatS r;
  #include "RAminPA.ipp"
  return r;
}

RAfloatD min(const int& a, const RAfloatD& b) {
  RAfloatD r;
  #include "RAminPA.ipp"
  return r;
}

RAfloatS min(const float& a, const RAfloatS& b) {
  RAfloatS r;
  #include "RAminPA.ipp"
  return r;
}

RAfloatD min(const float& a, const RAfloatD& b) {
  RAfloatD r;
  #include "RAminPA.ipp"
  return r;
}

RAfloatD min(const double& a, const RAfloatS& b) {
  RAfloatD r;
  #include "RAminPA.ipp"
  return r;
}

RAfloatD min(const double& a, const RAfloatD& b) {
  RAfloatD r;
  #include "RAminPA.ipp"
  return r;
}

