// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAmin_INCLUDE_
#define _RAmin_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  RAfloatS min(const RAfloatS& a, const RAfloatS& b);
  RAfloatD min(const RAfloatS& a, const RAfloatD& b);
  RAfloatD min(const RAfloatD& a, const RAfloatS& b);
  RAfloatD min(const RAfloatD& a, const RAfloatD& b);
  RAfloatS min(const RAfloatS& a, const int& b);
  RAfloatS min(const RAfloatS& a, const float& b);
  RAfloatD min(const RAfloatS& a, const double& b);
  RAfloatD min(const RAfloatD& a, const int& b);
  RAfloatD min(const RAfloatD& a, const float& b);
  RAfloatD min(const RAfloatD& a, const double& b);
  RAfloatS min(const int& a, const RAfloatS& b);
  RAfloatD min(const int& a, const RAfloatD& b);
  RAfloatS min(const float& a, const RAfloatS& b);
  RAfloatD min(const float& a, const RAfloatD& b);
  RAfloatD min(const double& a, const RAfloatS& b);
  RAfloatD min(const double& a, const RAfloatD& b);
#endif
