// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RApow_INCLUDE_
#define _RApow_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  #include "RAmult.hpp"
  #include "RAlog.hpp"
  #include "RAexp.hpp"
  RAfloatD pow(const RAfloatD& a, const RAfloatD& b);
  RAfloatD pow(const RAfloatD& a, const double& b);
  RAfloatD pow(const double& a, const RAfloatD& b);
#endif
