// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAsin_INCLUDE_
#define _RAsin_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  RAfloatS sin(const RAfloatS& a);
  RAfloatD sin(const RAfloatD& a);
#endif
