// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAsin.hpp"

RAfloatS sin(const RAfloatS& a) {
  RAfloatS s;
  RAfloatS c;
  RAfloatS t;
  #include "RAsincos.ipp"
  return s;
}

RAfloatD sin(const RAfloatD& a) {
  RAfloatD s;
  RAfloatD c;
  RAfloatD t;
  #include "RAsincos.ipp"
  return s;
}

