// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAsinh.hpp"

RAfloatS sinh(const RAfloatS& a) {
  RAfloatS s;
  RAfloatS c;
  RAfloatS t;
  #include "RAsinhcosh.ipp"
  return s;
}

RAfloatD sinh(const RAfloatD& a) {
  RAfloatD s;
  RAfloatD c;
  RAfloatD t;
  #include "RAsinhcosh.ipp"
  return s;
}

