// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAsinh_INCLUDE_
#define _RAsinh_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  RAfloatS sinh(const RAfloatS& a);
  RAfloatD sinh(const RAfloatD& a);
#endif
