// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAsqrt_INCLUDE_
#define _RAsqrt_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  RAfloatS sqrt(const RAfloatS& a);
  RAfloatD sqrt(const RAfloatD& a);
#endif
