// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAtan_INCLUDE_
#define _RAtan_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  #include "RAdiv.hpp"
  #include "RAsin.hpp"
  #include "RAcos.hpp"
  RAfloatS tan(const RAfloatS& a);
  RAfloatD tan(const RAfloatD& a);
#endif
