// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RAuminus.hpp"

RAfloatS operator -(const RAfloatS& a) {
  RAfloatS r;
  #include "RAuminus.ipp"
  return r;
}

RAfloatD operator -(const RAfloatD& a) {
  RAfloatD r;
  #include "RAuminus.ipp"
  return r;
}

