// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RAuminus_INCLUDE_
#define _RAuminus_INCLUDE_
  #include "RAprec.hpp"
  #include "RAtypes.hpp"
  RAfloatS operator -(const RAfloatS& a);
  RAfloatD operator -(const RAfloatD& a);
#endif
