! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAacos
  use RAprec
  use RAtypes
  use RAsqrt
  use RAdiv
  use RAmult
  use RAsub
  use RAuminus
  implicit none
  interface acos
    module procedure acosRArealS
    module procedure acosRArealD
  end interface acos
contains 
  elemental function acosRArealS(a) result(r)
    type(RArealS),intent(in)::a
    type(RArealS)::r
    type(RArealS)::h
    type(RArealS)::t
    include 'RAacos.i90'
  end function acosRArealS
  elemental function acosRArealD(a) result(r)
    type(RArealD),intent(in)::a
    type(RArealD)::r
    type(RArealD)::h
    type(RArealD)::t
    include 'RAacos.i90'
  end function acosRArealD
end module RAacos
