! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAadd
  use RAprec
  use RAtypes
  implicit none
  interface operator(+)
    module procedure addRArealSRArealS
    module procedure addRArealSRArealD
    module procedure addRArealSRAcomplexS
    module procedure addRArealSRAcomplexD
    module procedure addRArealDRArealS
    module procedure addRArealDRArealD
    module procedure addRArealDRAcomplexS
    module procedure addRArealDRAcomplexD
    module procedure addRAcomplexSRArealS
    module procedure addRAcomplexSRArealD
    module procedure addRAcomplexSRAcomplexS
    module procedure addRAcomplexSRAcomplexD
    module procedure addRAcomplexDRArealS
    module procedure addRAcomplexDRArealD
    module procedure addRAcomplexDRAcomplexS
    module procedure addRAcomplexDRAcomplexD
    module procedure addRArealSinteger
    module procedure addRArealSrealS
    module procedure addRArealSrealD
    module procedure addRArealScomplexS
    module procedure addRArealScomplexD
    module procedure addRArealDinteger
    module procedure addRArealDrealS
    module procedure addRArealDrealD
    module procedure addRArealDcomplexS
    module procedure addRArealDcomplexD
    module procedure addRAcomplexSinteger
    module procedure addRAcomplexSrealS
    module procedure addRAcomplexSrealD
    module procedure addRAcomplexScomplexS
    module procedure addRAcomplexScomplexD
    module procedure addRAcomplexDinteger
    module procedure addRAcomplexDrealS
    module procedure addRAcomplexDrealD
    module procedure addRAcomplexDcomplexS
    module procedure addRAcomplexDcomplexD
    module procedure addintegerRArealS
    module procedure addintegerRArealD
    module procedure addintegerRAcomplexS
    module procedure addintegerRAcomplexD
    module procedure addrealSRArealS
    module procedure addrealSRArealD
    module procedure addrealSRAcomplexS
    module procedure addrealSRAcomplexD
    module procedure addrealDRArealS
    module procedure addrealDRArealD
    module procedure addrealDRAcomplexS
    module procedure addrealDRAcomplexD
    module procedure addcomplexSRArealS
    module procedure addcomplexSRArealD
    module procedure addcomplexSRAcomplexS
    module procedure addcomplexSRAcomplexD
    module procedure addcomplexDRArealS
    module procedure addcomplexDRArealD
    module procedure addcomplexDRAcomplexS
    module procedure addcomplexDRAcomplexD
  end interface 
contains 
  elemental function addRArealSRArealS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAaddAA.i90'
  end function addRArealSRArealS
  elemental function addRArealSRArealD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAaddAA.i90'
  end function addRArealSRArealD
  elemental function addRArealSRAcomplexS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAaddAA.i90'
  end function addRArealSRAcomplexS
  elemental function addRArealSRAcomplexD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAA.i90'
  end function addRArealSRAcomplexD
  elemental function addRArealDRArealS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealD)::r
    include 'RAaddAA.i90'
  end function addRArealDRArealS
  elemental function addRArealDRArealD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAaddAA.i90'
  end function addRArealDRArealD
  elemental function addRArealDRAcomplexS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAA.i90'
  end function addRArealDRAcomplexS
  elemental function addRArealDRAcomplexD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAA.i90'
  end function addRArealDRAcomplexD
  elemental function addRAcomplexSRArealS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAaddAA.i90'
  end function addRAcomplexSRArealS
  elemental function addRAcomplexSRArealD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAA.i90'
  end function addRAcomplexSRArealD
  elemental function addRAcomplexSRAcomplexS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAaddAA.i90'
  end function addRAcomplexSRAcomplexS
  elemental function addRAcomplexSRAcomplexD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAA.i90'
  end function addRAcomplexSRAcomplexD
  elemental function addRAcomplexDRArealS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAA.i90'
  end function addRAcomplexDRArealS
  elemental function addRAcomplexDRArealD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAA.i90'
  end function addRAcomplexDRArealD
  elemental function addRAcomplexDRAcomplexS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAA.i90'
  end function addRAcomplexDRAcomplexS
  elemental function addRAcomplexDRAcomplexD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAA.i90'
  end function addRAcomplexDRAcomplexD
  elemental function addRArealSinteger(a,b) result(r)
    type(RArealS),intent(in)::a
    integer,intent(in)::b
    type(RArealS)::r
    include 'RAaddAP.i90'
  end function addRArealSinteger
  elemental function addRArealSrealS(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealS)::r
    include 'RAaddAP.i90'
  end function addRArealSrealS
  elemental function addRArealSrealD(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    include 'RAaddAP.i90'
  end function addRArealSrealD
  elemental function addRArealScomplexS(a,b) result(r)
    type(RArealS),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexS)::r
    include 'RAaddAP.i90'
  end function addRArealScomplexS
  elemental function addRArealScomplexD(a,b) result(r)
    type(RArealS),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAP.i90'
  end function addRArealScomplexD
  elemental function addRArealDinteger(a,b) result(r)
    type(RArealD),intent(in)::a
    integer,intent(in)::b
    type(RArealD)::r
    include 'RAaddAP.i90'
  end function addRArealDinteger
  elemental function addRArealDrealS(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealD)::r
    include 'RAaddAP.i90'
  end function addRArealDrealS
  elemental function addRArealDrealD(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    include 'RAaddAP.i90'
  end function addRArealDrealD
  elemental function addRArealDcomplexS(a,b) result(r)
    type(RArealD),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAP.i90'
  end function addRArealDcomplexS
  elemental function addRArealDcomplexD(a,b) result(r)
    type(RArealD),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAP.i90'
  end function addRArealDcomplexD
  elemental function addRAcomplexSinteger(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    integer,intent(in)::b
    type(RAcomplexS)::r
    include 'RAaddAP.i90'
  end function addRAcomplexSinteger
  elemental function addRAcomplexSrealS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RAcomplexS)::r
    include 'RAaddAP.i90'
  end function addRAcomplexSrealS
  elemental function addRAcomplexSrealD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAP.i90'
  end function addRAcomplexSrealD
  elemental function addRAcomplexScomplexS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexS)::r
    include 'RAaddAP.i90'
  end function addRAcomplexScomplexS
  elemental function addRAcomplexScomplexD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAP.i90'
  end function addRAcomplexScomplexD
  elemental function addRAcomplexDinteger(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    integer,intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAP.i90'
  end function addRAcomplexDinteger
  elemental function addRAcomplexDrealS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAP.i90'
  end function addRAcomplexDrealS
  elemental function addRAcomplexDrealD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAP.i90'
  end function addRAcomplexDrealD
  elemental function addRAcomplexDcomplexS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAP.i90'
  end function addRAcomplexDcomplexS
  elemental function addRAcomplexDcomplexD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddAP.i90'
  end function addRAcomplexDcomplexD
  elemental function addintegerRArealS(a,b) result(r)
    integer,intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAaddPA.i90'
  end function addintegerRArealS
  elemental function addintegerRArealD(a,b) result(r)
    integer,intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAaddPA.i90'
  end function addintegerRArealD
  elemental function addintegerRAcomplexS(a,b) result(r)
    integer,intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAaddPA.i90'
  end function addintegerRAcomplexS
  elemental function addintegerRAcomplexD(a,b) result(r)
    integer,intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddPA.i90'
  end function addintegerRAcomplexD
  elemental function addrealSRArealS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAaddPA.i90'
  end function addrealSRArealS
  elemental function addrealSRArealD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAaddPA.i90'
  end function addrealSRArealD
  elemental function addrealSRAcomplexS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAaddPA.i90'
  end function addrealSRAcomplexS
  elemental function addrealSRAcomplexD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddPA.i90'
  end function addrealSRAcomplexD
  elemental function addrealDRArealS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealD)::r
    include 'RAaddPA.i90'
  end function addrealDRArealS
  elemental function addrealDRArealD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAaddPA.i90'
  end function addrealDRArealD
  elemental function addrealDRAcomplexS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddPA.i90'
  end function addrealDRAcomplexS
  elemental function addrealDRAcomplexD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddPA.i90'
  end function addrealDRAcomplexD
  elemental function addcomplexSRArealS(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAaddPA.i90'
  end function addcomplexSRArealS
  elemental function addcomplexSRArealD(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddPA.i90'
  end function addcomplexSRArealD
  elemental function addcomplexSRAcomplexS(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAaddPA.i90'
  end function addcomplexSRAcomplexS
  elemental function addcomplexSRAcomplexD(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddPA.i90'
  end function addcomplexSRAcomplexD
  elemental function addcomplexDRArealS(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddPA.i90'
  end function addcomplexDRArealS
  elemental function addcomplexDRArealD(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddPA.i90'
  end function addcomplexDRArealD
  elemental function addcomplexDRAcomplexS(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddPA.i90'
  end function addcomplexDRAcomplexS
  elemental function addcomplexDRAcomplexD(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAaddPA.i90'
  end function addcomplexDRAcomplexD
end module RAadd
