! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAasgn
  use RAprec
  use RAtypes
  implicit none
  interface assignment(=)
    module procedure RAasgnRArealDRArealS
    module procedure RAasgnRAcomplexSRArealS
    module procedure RAasgnRAcomplexDRArealS
    module procedure RAasgnRAcomplexDRArealD
    module procedure RAasgnRAcomplexDRAcomplexS
    module procedure RAasgnRArealSinteger
    module procedure RAasgnRArealSrealS
    module procedure RAasgnRArealDinteger
    module procedure RAasgnRArealDrealS
    module procedure RAasgnRArealDrealD
    module procedure RAasgnRAcomplexSinteger
    module procedure RAasgnRAcomplexSrealS
    module procedure RAasgnRAcomplexScomplexS
    module procedure RAasgnRAcomplexDinteger
    module procedure RAasgnRAcomplexDrealS
    module procedure RAasgnRAcomplexDrealD
    module procedure RAasgnRAcomplexDcomplexS
    module procedure RAasgnRAcomplexDcomplexD
  end interface 
contains 
  elemental subroutine RAasgnRArealDRArealS(l,r)
    type(RArealD),intent(out)::l
    type(RArealS),intent(in)::r
    include 'RAasgnA.i90'
  end subroutine RAasgnRArealDRArealS
  elemental subroutine RAasgnRAcomplexSRArealS(l,r)
    type(RAcomplexS),intent(out)::l
    type(RArealS),intent(in)::r
    include 'RAasgnA.i90'
  end subroutine RAasgnRAcomplexSRArealS
  elemental subroutine RAasgnRAcomplexDRArealS(l,r)
    type(RAcomplexD),intent(out)::l
    type(RArealS),intent(in)::r
    include 'RAasgnA.i90'
  end subroutine RAasgnRAcomplexDRArealS
  elemental subroutine RAasgnRAcomplexDRArealD(l,r)
    type(RAcomplexD),intent(out)::l
    type(RArealD),intent(in)::r
    include 'RAasgnA.i90'
  end subroutine RAasgnRAcomplexDRArealD
  elemental subroutine RAasgnRAcomplexDRAcomplexS(l,r)
    type(RAcomplexD),intent(out)::l
    type(RAcomplexS),intent(in)::r
    include 'RAasgnA.i90'
  end subroutine RAasgnRAcomplexDRAcomplexS
  elemental subroutine RAasgnRArealSinteger(l,r)
    type(RArealS),intent(out)::l
    integer,intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRArealSinteger
  elemental subroutine RAasgnRArealSrealS(l,r)
    type(RArealS),intent(out)::l
    real(kind=RAsKind),intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRArealSrealS
  elemental subroutine RAasgnRArealDinteger(l,r)
    type(RArealD),intent(out)::l
    integer,intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRArealDinteger
  elemental subroutine RAasgnRArealDrealS(l,r)
    type(RArealD),intent(out)::l
    real(kind=RAsKind),intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRArealDrealS
  elemental subroutine RAasgnRArealDrealD(l,r)
    type(RArealD),intent(out)::l
    real(kind=RAdKind),intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRArealDrealD
  elemental subroutine RAasgnRAcomplexSinteger(l,r)
    type(RAcomplexS),intent(out)::l
    integer,intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRAcomplexSinteger
  elemental subroutine RAasgnRAcomplexSrealS(l,r)
    type(RAcomplexS),intent(out)::l
    real(kind=RAsKind),intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRAcomplexSrealS
  elemental subroutine RAasgnRAcomplexScomplexS(l,r)
    type(RAcomplexS),intent(out)::l
    complex(kind=RAsKind),intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRAcomplexScomplexS
  elemental subroutine RAasgnRAcomplexDinteger(l,r)
    type(RAcomplexD),intent(out)::l
    integer,intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRAcomplexDinteger
  elemental subroutine RAasgnRAcomplexDrealS(l,r)
    type(RAcomplexD),intent(out)::l
    real(kind=RAsKind),intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRAcomplexDrealS
  elemental subroutine RAasgnRAcomplexDrealD(l,r)
    type(RAcomplexD),intent(out)::l
    real(kind=RAdKind),intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRAcomplexDrealD
  elemental subroutine RAasgnRAcomplexDcomplexS(l,r)
    type(RAcomplexD),intent(out)::l
    complex(kind=RAsKind),intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRAcomplexDcomplexS
  elemental subroutine RAasgnRAcomplexDcomplexD(l,r)
    type(RAcomplexD),intent(out)::l
    complex(kind=RAdKind),intent(in)::r
    include 'RAasgnP.i90'
  end subroutine RAasgnRAcomplexDcomplexD
end module RAasgn
