! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAasin
  use RAprec
  use RAtypes
  use RAsqrt
  use RAdiv
  use RAmult
  use RAsub
  implicit none
  interface asin
    module procedure asinRArealS
    module procedure asinRArealD
  end interface asin
contains 
  elemental function asinRArealS(a) result(r)
    type(RArealS),intent(in)::a
    type(RArealS)::r
    type(RArealS)::h
    type(RArealS)::t
    include 'RAasin.i90'
  end function asinRArealS
  elemental function asinRArealD(a) result(r)
    type(RArealD),intent(in)::a
    type(RArealD)::r
    type(RArealD)::h
    type(RArealD)::t
    include 'RAasin.i90'
  end function asinRArealD
end module RAasin
