! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAatan
  use RAprec
  use RAtypes
  use RAadd
  use RAdiv
  use RAmult
  implicit none
  interface atan
    module procedure atanRArealS
    module procedure atanRArealD
  end interface atan
contains 
  elemental function atanRArealS(a) result(r)
    type(RArealS),intent(in)::a
    type(RArealS)::r
    type(RArealS)::y
    type(RArealS)::s
    real(kind=RAsKind)::one
    include 'RAatan.i90'
  end function atanRArealS
  elemental function atanRArealD(a) result(r)
    type(RArealD),intent(in)::a
    type(RArealD)::r
    type(RArealD)::y
    type(RArealD)::s
    real(kind=RAdKind)::one
    include 'RAatan.i90'
  end function atanRArealD
end module RAatan
