! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAcosh
  use RAprec
  use RAtypes
  implicit none
  interface cosh
    module procedure coshRArealS
    module procedure coshRArealD
  end interface cosh
contains 
  elemental function coshRArealS(a) result(c)
    type(RArealS),intent(in)::a
    type(RArealS)::c
    type(RArealS)::s
    type(RArealS)::t
    include 'RAsinhcosh.i90'
  end function coshRArealS
  elemental function coshRArealD(a) result(c)
    type(RArealD),intent(in)::a
    type(RArealD)::c
    type(RArealD)::s
    type(RArealD)::t
    include 'RAsinhcosh.i90'
  end function coshRArealD
end module RAcosh
