! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAeq
  use RAprec
  use RAtypes
  implicit none
  interface operator(==)
    module procedure eqRArealSRArealS
    module procedure eqRArealSRArealD
    module procedure eqRArealSRAcomplexS
    module procedure eqRArealSRAcomplexD
    module procedure eqRArealDRArealS
    module procedure eqRArealDRArealD
    module procedure eqRArealDRAcomplexS
    module procedure eqRArealDRAcomplexD
    module procedure eqRAcomplexSRArealS
    module procedure eqRAcomplexSRArealD
    module procedure eqRAcomplexSRAcomplexS
    module procedure eqRAcomplexSRAcomplexD
    module procedure eqRAcomplexDRArealS
    module procedure eqRAcomplexDRArealD
    module procedure eqRAcomplexDRAcomplexS
    module procedure eqRAcomplexDRAcomplexD
    module procedure eqRArealSinteger
    module procedure eqRArealSrealS
    module procedure eqRArealSrealD
    module procedure eqRArealScomplexS
    module procedure eqRArealScomplexD
    module procedure eqRArealDinteger
    module procedure eqRArealDrealS
    module procedure eqRArealDrealD
    module procedure eqRArealDcomplexS
    module procedure eqRArealDcomplexD
    module procedure eqRAcomplexSinteger
    module procedure eqRAcomplexSrealS
    module procedure eqRAcomplexSrealD
    module procedure eqRAcomplexScomplexS
    module procedure eqRAcomplexScomplexD
    module procedure eqRAcomplexDinteger
    module procedure eqRAcomplexDrealS
    module procedure eqRAcomplexDrealD
    module procedure eqRAcomplexDcomplexS
    module procedure eqRAcomplexDcomplexD
    module procedure eqintegerRArealS
    module procedure eqintegerRArealD
    module procedure eqintegerRAcomplexS
    module procedure eqintegerRAcomplexD
    module procedure eqrealSRArealS
    module procedure eqrealSRArealD
    module procedure eqrealSRAcomplexS
    module procedure eqrealSRAcomplexD
    module procedure eqrealDRArealS
    module procedure eqrealDRArealD
    module procedure eqrealDRAcomplexS
    module procedure eqrealDRAcomplexD
    module procedure eqcomplexSRArealS
    module procedure eqcomplexSRArealD
    module procedure eqcomplexSRAcomplexS
    module procedure eqcomplexSRAcomplexD
    module procedure eqcomplexDRArealS
    module procedure eqcomplexDRArealD
    module procedure eqcomplexDRAcomplexS
    module procedure eqcomplexDRAcomplexD
  end interface 
contains 
  elemental function eqRArealSRArealS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRArealSRArealS
  elemental function eqRArealSRArealD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRArealSRArealD
  elemental function eqRArealSRAcomplexS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRArealSRAcomplexS
  elemental function eqRArealSRAcomplexD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRArealSRAcomplexD
  elemental function eqRArealDRArealS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRArealDRArealS
  elemental function eqRArealDRArealD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRArealDRArealD
  elemental function eqRArealDRAcomplexS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRArealDRAcomplexS
  elemental function eqRArealDRAcomplexD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRArealDRAcomplexD
  elemental function eqRAcomplexSRArealS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRAcomplexSRArealS
  elemental function eqRAcomplexSRArealD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRAcomplexSRArealD
  elemental function eqRAcomplexSRAcomplexS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRAcomplexSRAcomplexS
  elemental function eqRAcomplexSRAcomplexD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRAcomplexSRAcomplexD
  elemental function eqRAcomplexDRArealS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRAcomplexDRArealS
  elemental function eqRAcomplexDRArealD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRAcomplexDRArealD
  elemental function eqRAcomplexDRAcomplexS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRAcomplexDRAcomplexS
  elemental function eqRAcomplexDRAcomplexD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAeqAA.i90'
  end function eqRAcomplexDRAcomplexD
  elemental function eqRArealSinteger(a,b) result(r)
    type(RArealS),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRArealSinteger
  elemental function eqRArealSrealS(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRArealSrealS
  elemental function eqRArealSrealD(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRArealSrealD
  elemental function eqRArealScomplexS(a,b) result(r)
    type(RArealS),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRArealScomplexS
  elemental function eqRArealScomplexD(a,b) result(r)
    type(RArealS),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRArealScomplexD
  elemental function eqRArealDinteger(a,b) result(r)
    type(RArealD),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRArealDinteger
  elemental function eqRArealDrealS(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRArealDrealS
  elemental function eqRArealDrealD(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRArealDrealD
  elemental function eqRArealDcomplexS(a,b) result(r)
    type(RArealD),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRArealDcomplexS
  elemental function eqRArealDcomplexD(a,b) result(r)
    type(RArealD),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRArealDcomplexD
  elemental function eqRAcomplexSinteger(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRAcomplexSinteger
  elemental function eqRAcomplexSrealS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRAcomplexSrealS
  elemental function eqRAcomplexSrealD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRAcomplexSrealD
  elemental function eqRAcomplexScomplexS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRAcomplexScomplexS
  elemental function eqRAcomplexScomplexD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRAcomplexScomplexD
  elemental function eqRAcomplexDinteger(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRAcomplexDinteger
  elemental function eqRAcomplexDrealS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRAcomplexDrealS
  elemental function eqRAcomplexDrealD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRAcomplexDrealD
  elemental function eqRAcomplexDcomplexS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRAcomplexDcomplexS
  elemental function eqRAcomplexDcomplexD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAeqAP.i90'
  end function eqRAcomplexDcomplexD
  elemental function eqintegerRArealS(a,b) result(r)
    integer,intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqintegerRArealS
  elemental function eqintegerRArealD(a,b) result(r)
    integer,intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqintegerRArealD
  elemental function eqintegerRAcomplexS(a,b) result(r)
    integer,intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqintegerRAcomplexS
  elemental function eqintegerRAcomplexD(a,b) result(r)
    integer,intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqintegerRAcomplexD
  elemental function eqrealSRArealS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqrealSRArealS
  elemental function eqrealSRArealD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqrealSRArealD
  elemental function eqrealSRAcomplexS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqrealSRAcomplexS
  elemental function eqrealSRAcomplexD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqrealSRAcomplexD
  elemental function eqrealDRArealS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqrealDRArealS
  elemental function eqrealDRArealD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqrealDRArealD
  elemental function eqrealDRAcomplexS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqrealDRAcomplexS
  elemental function eqrealDRAcomplexD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqrealDRAcomplexD
  elemental function eqcomplexSRArealS(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqcomplexSRArealS
  elemental function eqcomplexSRArealD(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqcomplexSRArealD
  elemental function eqcomplexSRAcomplexS(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqcomplexSRAcomplexS
  elemental function eqcomplexSRAcomplexD(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqcomplexSRAcomplexD
  elemental function eqcomplexDRArealS(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqcomplexDRArealS
  elemental function eqcomplexDRArealD(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqcomplexDRArealD
  elemental function eqcomplexDRAcomplexS(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqcomplexDRAcomplexS
  elemental function eqcomplexDRAcomplexD(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAeqPA.i90'
  end function eqcomplexDRAcomplexD
end module RAeq
