! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAexp
  use RAprec
  use RAtypes
  implicit none
  interface exp
    module procedure expRArealS
    module procedure expRArealD
    module procedure expRAcomplexS
    module procedure expRAcomplexD
  end interface exp
contains 
  elemental function expRArealS(a) result(r)
    type(RArealS),intent(in)::a
    type(RArealS)::r
    type(RArealS)::s
    type(RArealS)::t
    include 'RAexp.i90'
  end function expRArealS
  elemental function expRArealD(a) result(r)
    type(RArealD),intent(in)::a
    type(RArealD)::r
    type(RArealD)::s
    type(RArealD)::t
    include 'RAexp.i90'
  end function expRArealD
  elemental function expRAcomplexS(a) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexS)::r
    type(RAcomplexS)::s
    type(RAcomplexS)::t
    include 'RAexp.i90'
  end function expRAcomplexS
  elemental function expRAcomplexD(a) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexD)::r
    type(RAcomplexD)::s
    type(RAcomplexD)::t
    include 'RAexp.i90'
  end function expRAcomplexD
end module RAexp
