! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAge
  use RAprec
  use RAtypes
  implicit none
  interface operator(>=)
    module procedure geRArealSRArealS
    module procedure geRArealSRArealD
    module procedure geRArealDRArealS
    module procedure geRArealDRArealD
    module procedure geRArealSinteger
    module procedure geRArealSrealS
    module procedure geRArealSrealD
    module procedure geRArealDinteger
    module procedure geRArealDrealS
    module procedure geRArealDrealD
    module procedure geintegerRArealS
    module procedure geintegerRArealD
    module procedure gerealSRArealS
    module procedure gerealSRArealD
    module procedure gerealDRArealS
    module procedure gerealDRArealD
  end interface 
contains 
  elemental function geRArealSRArealS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAgeAA.i90'
  end function geRArealSRArealS
  elemental function geRArealSRArealD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAgeAA.i90'
  end function geRArealSRArealD
  elemental function geRArealDRArealS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAgeAA.i90'
  end function geRArealDRArealS
  elemental function geRArealDRArealD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAgeAA.i90'
  end function geRArealDRArealD
  elemental function geRArealSinteger(a,b) result(r)
    type(RArealS),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAgeAP.i90'
  end function geRArealSinteger
  elemental function geRArealSrealS(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAgeAP.i90'
  end function geRArealSrealS
  elemental function geRArealSrealD(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAgeAP.i90'
  end function geRArealSrealD
  elemental function geRArealDinteger(a,b) result(r)
    type(RArealD),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAgeAP.i90'
  end function geRArealDinteger
  elemental function geRArealDrealS(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAgeAP.i90'
  end function geRArealDrealS
  elemental function geRArealDrealD(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAgeAP.i90'
  end function geRArealDrealD
  elemental function geintegerRArealS(a,b) result(r)
    integer,intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAgePA.i90'
  end function geintegerRArealS
  elemental function geintegerRArealD(a,b) result(r)
    integer,intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAgePA.i90'
  end function geintegerRArealD
  elemental function gerealSRArealS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAgePA.i90'
  end function gerealSRArealS
  elemental function gerealSRArealD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAgePA.i90'
  end function gerealSRArealD
  elemental function gerealDRArealS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAgePA.i90'
  end function gerealDRArealS
  elemental function gerealDRArealD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAgePA.i90'
  end function gerealDRArealD
end module RAge
