! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAgt
  use RAprec
  use RAtypes
  implicit none
  interface operator(>)
    module procedure gtRArealSRArealS
    module procedure gtRArealSRArealD
    module procedure gtRArealDRArealS
    module procedure gtRArealDRArealD
    module procedure gtRArealSinteger
    module procedure gtRArealSrealS
    module procedure gtRArealSrealD
    module procedure gtRArealDinteger
    module procedure gtRArealDrealS
    module procedure gtRArealDrealD
    module procedure gtintegerRArealS
    module procedure gtintegerRArealD
    module procedure gtrealSRArealS
    module procedure gtrealSRArealD
    module procedure gtrealDRArealS
    module procedure gtrealDRArealD
  end interface 
contains 
  elemental function gtRArealSRArealS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAgtAA.i90'
  end function gtRArealSRArealS
  elemental function gtRArealSRArealD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAgtAA.i90'
  end function gtRArealSRArealD
  elemental function gtRArealDRArealS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAgtAA.i90'
  end function gtRArealDRArealS
  elemental function gtRArealDRArealD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAgtAA.i90'
  end function gtRArealDRArealD
  elemental function gtRArealSinteger(a,b) result(r)
    type(RArealS),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAgtAP.i90'
  end function gtRArealSinteger
  elemental function gtRArealSrealS(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAgtAP.i90'
  end function gtRArealSrealS
  elemental function gtRArealSrealD(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAgtAP.i90'
  end function gtRArealSrealD
  elemental function gtRArealDinteger(a,b) result(r)
    type(RArealD),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAgtAP.i90'
  end function gtRArealDinteger
  elemental function gtRArealDrealS(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAgtAP.i90'
  end function gtRArealDrealS
  elemental function gtRArealDrealD(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAgtAP.i90'
  end function gtRArealDrealD
  elemental function gtintegerRArealS(a,b) result(r)
    integer,intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAgtPA.i90'
  end function gtintegerRArealS
  elemental function gtintegerRArealD(a,b) result(r)
    integer,intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAgtPA.i90'
  end function gtintegerRArealD
  elemental function gtrealSRArealS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAgtPA.i90'
  end function gtrealSRArealS
  elemental function gtrealSRArealD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAgtPA.i90'
  end function gtrealSRArealD
  elemental function gtrealDRArealS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAgtPA.i90'
  end function gtrealDRArealS
  elemental function gtrealDRArealD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAgtPA.i90'
  end function gtrealDRArealD
end module RAgt
