! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAle
  use RAprec
  use RAtypes
  implicit none
  interface operator(<=)
    module procedure leRArealSRArealS
    module procedure leRArealSRArealD
    module procedure leRArealDRArealS
    module procedure leRArealDRArealD
    module procedure leRArealSinteger
    module procedure leRArealSrealS
    module procedure leRArealSrealD
    module procedure leRArealDinteger
    module procedure leRArealDrealS
    module procedure leRArealDrealD
    module procedure leintegerRArealS
    module procedure leintegerRArealD
    module procedure lerealSRArealS
    module procedure lerealSRArealD
    module procedure lerealDRArealS
    module procedure lerealDRArealD
  end interface 
contains 
  elemental function leRArealSRArealS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAleAA.i90'
  end function leRArealSRArealS
  elemental function leRArealSRArealD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAleAA.i90'
  end function leRArealSRArealD
  elemental function leRArealDRArealS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAleAA.i90'
  end function leRArealDRArealS
  elemental function leRArealDRArealD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAleAA.i90'
  end function leRArealDRArealD
  elemental function leRArealSinteger(a,b) result(r)
    type(RArealS),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAleAP.i90'
  end function leRArealSinteger
  elemental function leRArealSrealS(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAleAP.i90'
  end function leRArealSrealS
  elemental function leRArealSrealD(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAleAP.i90'
  end function leRArealSrealD
  elemental function leRArealDinteger(a,b) result(r)
    type(RArealD),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAleAP.i90'
  end function leRArealDinteger
  elemental function leRArealDrealS(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAleAP.i90'
  end function leRArealDrealS
  elemental function leRArealDrealD(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAleAP.i90'
  end function leRArealDrealD
  elemental function leintegerRArealS(a,b) result(r)
    integer,intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAlePA.i90'
  end function leintegerRArealS
  elemental function leintegerRArealD(a,b) result(r)
    integer,intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAlePA.i90'
  end function leintegerRArealD
  elemental function lerealSRArealS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAlePA.i90'
  end function lerealSRArealS
  elemental function lerealSRArealD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAlePA.i90'
  end function lerealSRArealD
  elemental function lerealDRArealS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAlePA.i90'
  end function lerealDRArealS
  elemental function lerealDRArealD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAlePA.i90'
  end function lerealDRArealD
end module RAle
