! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAlog
  use RAprec
  use RAtypes
  implicit none
  interface log
    module procedure logRArealS
    module procedure logRArealD
    module procedure logRAcomplexS
    module procedure logRAcomplexD
  end interface log
contains 
  elemental function logRArealS(a) result(r)
    type(RArealS),intent(in)::a
    type(RArealS)::r
    type(RArealS)::s
    type(RArealS)::t
    real(kind=RAsKind)::recip
    include 'RAlog.i90'
  end function logRArealS
  elemental function logRArealD(a) result(r)
    type(RArealD),intent(in)::a
    type(RArealD)::r
    type(RArealD)::s
    type(RArealD)::t
    real(kind=RAdKind)::recip
    include 'RAlog.i90'
  end function logRArealD
  elemental function logRAcomplexS(a) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexS)::r
    type(RAcomplexS)::s
    type(RAcomplexS)::t
    complex(kind=RAsKind)::recip
    include 'RAlog.i90'
  end function logRAcomplexS
  elemental function logRAcomplexD(a) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexD)::r
    type(RAcomplexD)::s
    type(RAcomplexD)::t
    complex(kind=RAdKind)::recip
    include 'RAlog.i90'
  end function logRAcomplexD
end module RAlog
