! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAmaxval
  use RAprec
  use RAtypes
  implicit none
  interface maxval
    module procedure maxvalRArealS1
    module procedure maxvalRArealD1
    module procedure maxvalRArealS2
    module procedure maxvalRArealD2
    module procedure maxvalRArealS3
    module procedure maxvalRArealD3
    module procedure maxvalRArealS4
    module procedure maxvalRArealD4
    module procedure maxvalRArealS5
    module procedure maxvalRArealD5
    module procedure maxvalRArealS6
    module procedure maxvalRArealD6
    module procedure maxvalRArealS7
    module procedure maxvalRArealD7
  end interface maxval
contains 
  function maxvalRArealS1(a) result(r)
    type(RArealS),intent(in)::a(:)
    type(RArealS)::r
    integer::j(1)
    type(RArealS)::maxA
    include 'RAmaxval1.i90'
  end function maxvalRArealS1
  function maxvalRArealD1(a) result(r)
    type(RArealD),intent(in)::a(:)
    type(RArealD)::r
    integer::j(1)
    type(RArealD)::maxA
    include 'RAmaxval1.i90'
  end function maxvalRArealD1
  function maxvalRArealS2(a) result(r)
    type(RArealS),intent(in)::a(:,:)
    type(RArealS)::r
    integer::j(2)
    type(RArealS)::maxA
    include 'RAmaxval2.i90'
  end function maxvalRArealS2
  function maxvalRArealD2(a) result(r)
    type(RArealD),intent(in)::a(:,:)
    type(RArealD)::r
    integer::j(2)
    type(RArealD)::maxA
    include 'RAmaxval2.i90'
  end function maxvalRArealD2
  function maxvalRArealS3(a) result(r)
    type(RArealS),intent(in)::a(:,:,:)
    type(RArealS)::r
    integer::j(3)
    type(RArealS)::maxA
    include 'RAmaxval3.i90'
  end function maxvalRArealS3
  function maxvalRArealD3(a) result(r)
    type(RArealD),intent(in)::a(:,:,:)
    type(RArealD)::r
    integer::j(3)
    type(RArealD)::maxA
    include 'RAmaxval3.i90'
  end function maxvalRArealD3
  function maxvalRArealS4(a) result(r)
    type(RArealS),intent(in)::a(:,:,:,:)
    type(RArealS)::r
    integer::j(4)
    type(RArealS)::maxA
    include 'RAmaxval4.i90'
  end function maxvalRArealS4
  function maxvalRArealD4(a) result(r)
    type(RArealD),intent(in)::a(:,:,:,:)
    type(RArealD)::r
    integer::j(4)
    type(RArealD)::maxA
    include 'RAmaxval4.i90'
  end function maxvalRArealD4
  function maxvalRArealS5(a) result(r)
    type(RArealS),intent(in)::a(:,:,:,:,:)
    type(RArealS)::r
    integer::j(5)
    type(RArealS)::maxA
    include 'RAmaxval5.i90'
  end function maxvalRArealS5
  function maxvalRArealD5(a) result(r)
    type(RArealD),intent(in)::a(:,:,:,:,:)
    type(RArealD)::r
    integer::j(5)
    type(RArealD)::maxA
    include 'RAmaxval5.i90'
  end function maxvalRArealD5
  function maxvalRArealS6(a) result(r)
    type(RArealS),intent(in)::a(:,:,:,:,:,:)
    type(RArealS)::r
    integer::j(6)
    type(RArealS)::maxA
    include 'RAmaxval6.i90'
  end function maxvalRArealS6
  function maxvalRArealD6(a) result(r)
    type(RArealD),intent(in)::a(:,:,:,:,:,:)
    type(RArealD)::r
    integer::j(6)
    type(RArealD)::maxA
    include 'RAmaxval6.i90'
  end function maxvalRArealD6
  function maxvalRArealS7(a) result(r)
    type(RArealS),intent(in)::a(:,:,:,:,:,:,:)
    type(RArealS)::r
    integer::j(7)
    type(RArealS)::maxA
    include 'RAmaxval7.i90'
  end function maxvalRArealS7
  function maxvalRArealD7(a) result(r)
    type(RArealD),intent(in)::a(:,:,:,:,:,:,:)
    type(RArealD)::r
    integer::j(7)
    type(RArealD)::maxA
    include 'RAmaxval7.i90'
  end function maxvalRArealD7
end module RAmaxval
