! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAmatmul
  use RAprec
  use RAtypes
  use RAsum
  use RAmult
  implicit none
  interface matmul
    module procedure matmulRArealSRArealS22
    module procedure matmulRArealSRArealD22
    module procedure matmulRArealSRAcomplexS22
    module procedure matmulRArealSRAcomplexD22
    module procedure matmulRArealDRArealS22
    module procedure matmulRArealDRArealD22
    module procedure matmulRArealDRAcomplexS22
    module procedure matmulRArealDRAcomplexD22
    module procedure matmulRAcomplexSRArealS22
    module procedure matmulRAcomplexSRArealD22
    module procedure matmulRAcomplexSRAcomplexS22
    module procedure matmulRAcomplexSRAcomplexD22
    module procedure matmulRAcomplexDRArealS22
    module procedure matmulRAcomplexDRArealD22
    module procedure matmulRAcomplexDRAcomplexS22
    module procedure matmulRAcomplexDRAcomplexD22
    module procedure matmulRArealSinteger22
    module procedure matmulRArealSrealS22
    module procedure matmulRArealSrealD22
    module procedure matmulRArealScomplexS22
    module procedure matmulRArealScomplexD22
    module procedure matmulRArealDinteger22
    module procedure matmulRArealDrealS22
    module procedure matmulRArealDrealD22
    module procedure matmulRArealDcomplexS22
    module procedure matmulRArealDcomplexD22
    module procedure matmulRAcomplexSinteger22
    module procedure matmulRAcomplexSrealS22
    module procedure matmulRAcomplexSrealD22
    module procedure matmulRAcomplexScomplexS22
    module procedure matmulRAcomplexScomplexD22
    module procedure matmulRAcomplexDinteger22
    module procedure matmulRAcomplexDrealS22
    module procedure matmulRAcomplexDrealD22
    module procedure matmulRAcomplexDcomplexS22
    module procedure matmulRAcomplexDcomplexD22
    module procedure matmulintegerRArealS22
    module procedure matmulintegerRArealD22
    module procedure matmulintegerRAcomplexS22
    module procedure matmulintegerRAcomplexD22
    module procedure matmulrealSRArealS22
    module procedure matmulrealSRArealD22
    module procedure matmulrealSRAcomplexS22
    module procedure matmulrealSRAcomplexD22
    module procedure matmulrealDRArealS22
    module procedure matmulrealDRArealD22
    module procedure matmulrealDRAcomplexS22
    module procedure matmulrealDRAcomplexD22
    module procedure matmulcomplexSRArealS22
    module procedure matmulcomplexSRArealD22
    module procedure matmulcomplexSRAcomplexS22
    module procedure matmulcomplexSRAcomplexD22
    module procedure matmulcomplexDRArealS22
    module procedure matmulcomplexDRArealD22
    module procedure matmulcomplexDRAcomplexS22
    module procedure matmulcomplexDRAcomplexD22
    module procedure matmulRArealSRArealS12
    module procedure matmulRArealSRArealD12
    module procedure matmulRArealSRAcomplexS12
    module procedure matmulRArealSRAcomplexD12
    module procedure matmulRArealDRArealS12
    module procedure matmulRArealDRArealD12
    module procedure matmulRArealDRAcomplexS12
    module procedure matmulRArealDRAcomplexD12
    module procedure matmulRAcomplexSRArealS12
    module procedure matmulRAcomplexSRArealD12
    module procedure matmulRAcomplexSRAcomplexS12
    module procedure matmulRAcomplexSRAcomplexD12
    module procedure matmulRAcomplexDRArealS12
    module procedure matmulRAcomplexDRArealD12
    module procedure matmulRAcomplexDRAcomplexS12
    module procedure matmulRAcomplexDRAcomplexD12
    module procedure matmulRArealSinteger12
    module procedure matmulRArealSrealS12
    module procedure matmulRArealSrealD12
    module procedure matmulRArealScomplexS12
    module procedure matmulRArealScomplexD12
    module procedure matmulRArealDinteger12
    module procedure matmulRArealDrealS12
    module procedure matmulRArealDrealD12
    module procedure matmulRArealDcomplexS12
    module procedure matmulRArealDcomplexD12
    module procedure matmulRAcomplexSinteger12
    module procedure matmulRAcomplexSrealS12
    module procedure matmulRAcomplexSrealD12
    module procedure matmulRAcomplexScomplexS12
    module procedure matmulRAcomplexScomplexD12
    module procedure matmulRAcomplexDinteger12
    module procedure matmulRAcomplexDrealS12
    module procedure matmulRAcomplexDrealD12
    module procedure matmulRAcomplexDcomplexS12
    module procedure matmulRAcomplexDcomplexD12
    module procedure matmulintegerRArealS12
    module procedure matmulintegerRArealD12
    module procedure matmulintegerRAcomplexS12
    module procedure matmulintegerRAcomplexD12
    module procedure matmulrealSRArealS12
    module procedure matmulrealSRArealD12
    module procedure matmulrealSRAcomplexS12
    module procedure matmulrealSRAcomplexD12
    module procedure matmulrealDRArealS12
    module procedure matmulrealDRArealD12
    module procedure matmulrealDRAcomplexS12
    module procedure matmulrealDRAcomplexD12
    module procedure matmulcomplexSRArealS12
    module procedure matmulcomplexSRArealD12
    module procedure matmulcomplexSRAcomplexS12
    module procedure matmulcomplexSRAcomplexD12
    module procedure matmulcomplexDRArealS12
    module procedure matmulcomplexDRArealD12
    module procedure matmulcomplexDRAcomplexS12
    module procedure matmulcomplexDRAcomplexD12
    module procedure matmulRArealSRArealS21
    module procedure matmulRArealSRArealD21
    module procedure matmulRArealSRAcomplexS21
    module procedure matmulRArealSRAcomplexD21
    module procedure matmulRArealDRArealS21
    module procedure matmulRArealDRArealD21
    module procedure matmulRArealDRAcomplexS21
    module procedure matmulRArealDRAcomplexD21
    module procedure matmulRAcomplexSRArealS21
    module procedure matmulRAcomplexSRArealD21
    module procedure matmulRAcomplexSRAcomplexS21
    module procedure matmulRAcomplexSRAcomplexD21
    module procedure matmulRAcomplexDRArealS21
    module procedure matmulRAcomplexDRArealD21
    module procedure matmulRAcomplexDRAcomplexS21
    module procedure matmulRAcomplexDRAcomplexD21
    module procedure matmulRArealSinteger21
    module procedure matmulRArealSrealS21
    module procedure matmulRArealSrealD21
    module procedure matmulRArealScomplexS21
    module procedure matmulRArealScomplexD21
    module procedure matmulRArealDinteger21
    module procedure matmulRArealDrealS21
    module procedure matmulRArealDrealD21
    module procedure matmulRArealDcomplexS21
    module procedure matmulRArealDcomplexD21
    module procedure matmulRAcomplexSinteger21
    module procedure matmulRAcomplexSrealS21
    module procedure matmulRAcomplexSrealD21
    module procedure matmulRAcomplexScomplexS21
    module procedure matmulRAcomplexScomplexD21
    module procedure matmulRAcomplexDinteger21
    module procedure matmulRAcomplexDrealS21
    module procedure matmulRAcomplexDrealD21
    module procedure matmulRAcomplexDcomplexS21
    module procedure matmulRAcomplexDcomplexD21
    module procedure matmulintegerRArealS21
    module procedure matmulintegerRArealD21
    module procedure matmulintegerRAcomplexS21
    module procedure matmulintegerRAcomplexD21
    module procedure matmulrealSRArealS21
    module procedure matmulrealSRArealD21
    module procedure matmulrealSRAcomplexS21
    module procedure matmulrealSRAcomplexD21
    module procedure matmulrealDRArealS21
    module procedure matmulrealDRArealD21
    module procedure matmulrealDRAcomplexS21
    module procedure matmulrealDRAcomplexD21
    module procedure matmulcomplexSRArealS21
    module procedure matmulcomplexSRArealD21
    module procedure matmulcomplexSRAcomplexS21
    module procedure matmulcomplexSRAcomplexD21
    module procedure matmulcomplexDRArealS21
    module procedure matmulcomplexDRArealD21
    module procedure matmulcomplexDRAcomplexS21
    module procedure matmulcomplexDRAcomplexD21
  end interface matmul
contains 
  function matmulRArealSRArealS22(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:,:)
    type(RArealS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealSRArealS22
  function matmulRArealSRArealD22(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:,:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealSRArealD22
  function matmulRArealSRAcomplexS22(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealSRAcomplexS22
  function matmulRArealSRAcomplexD22(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealSRAcomplexD22
  function matmulRArealDRArealS22(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:,:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealDRArealS22
  function matmulRArealDRArealD22(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:,:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealDRArealD22
  function matmulRArealDRAcomplexS22(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealDRAcomplexS22
  function matmulRArealDRAcomplexD22(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealDRAcomplexD22
  function matmulRAcomplexSRArealS22(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexSRArealS22
  function matmulRAcomplexSRArealD22(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexSRArealD22
  function matmulRAcomplexSRAcomplexS22(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexSRAcomplexS22
  function matmulRAcomplexSRAcomplexD22(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexSRAcomplexD22
  function matmulRAcomplexDRArealS22(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexDRArealS22
  function matmulRAcomplexDRArealD22(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexDRArealD22
  function matmulRAcomplexDRAcomplexS22(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexDRAcomplexS22
  function matmulRAcomplexDRAcomplexD22(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexDRAcomplexD22
  function matmulRArealSinteger22(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    integer,intent(in)::b(:,:)
    type(RArealS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealSinteger22
  function matmulRArealSrealS22(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    real(kind=RAsKind),intent(in)::b(:,:)
    type(RArealS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealSrealS22
  function matmulRArealSrealD22(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    real(kind=RAdKind),intent(in)::b(:,:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealSrealD22
  function matmulRArealScomplexS22(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    complex(kind=RAsKind),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealScomplexS22
  function matmulRArealScomplexD22(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    complex(kind=RAdKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealScomplexD22
  function matmulRArealDinteger22(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    integer,intent(in)::b(:,:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealDinteger22
  function matmulRArealDrealS22(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    real(kind=RAsKind),intent(in)::b(:,:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealDrealS22
  function matmulRArealDrealD22(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    real(kind=RAdKind),intent(in)::b(:,:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealDrealD22
  function matmulRArealDcomplexS22(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    complex(kind=RAsKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealDcomplexS22
  function matmulRArealDcomplexD22(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    complex(kind=RAdKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRArealDcomplexD22
  function matmulRAcomplexSinteger22(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    integer,intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexSinteger22
  function matmulRAcomplexSrealS22(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    real(kind=RAsKind),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexSrealS22
  function matmulRAcomplexSrealD22(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    real(kind=RAdKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexSrealD22
  function matmulRAcomplexScomplexS22(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    complex(kind=RAsKind),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexScomplexS22
  function matmulRAcomplexScomplexD22(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    complex(kind=RAdKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexScomplexD22
  function matmulRAcomplexDinteger22(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    integer,intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexDinteger22
  function matmulRAcomplexDrealS22(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    real(kind=RAsKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexDrealS22
  function matmulRAcomplexDrealD22(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    real(kind=RAdKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexDrealD22
  function matmulRAcomplexDcomplexS22(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    complex(kind=RAsKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexDcomplexS22
  function matmulRAcomplexDcomplexD22(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    complex(kind=RAdKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulRAcomplexDcomplexD22
  function matmulintegerRArealS22(a,b) result(r)
    integer,intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:,:)
    type(RArealS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulintegerRArealS22
  function matmulintegerRArealD22(a,b) result(r)
    integer,intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:,:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulintegerRArealD22
  function matmulintegerRAcomplexS22(a,b) result(r)
    integer,intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulintegerRAcomplexS22
  function matmulintegerRAcomplexD22(a,b) result(r)
    integer,intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulintegerRAcomplexD22
  function matmulrealSRArealS22(a,b) result(r)
    real(kind=RAsKind),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:,:)
    type(RArealS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulrealSRArealS22
  function matmulrealSRArealD22(a,b) result(r)
    real(kind=RAsKind),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:,:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulrealSRArealD22
  function matmulrealSRAcomplexS22(a,b) result(r)
    real(kind=RAsKind),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulrealSRAcomplexS22
  function matmulrealSRAcomplexD22(a,b) result(r)
    real(kind=RAsKind),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulrealSRAcomplexD22
  function matmulrealDRArealS22(a,b) result(r)
    real(kind=RAdKind),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:,:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulrealDRArealS22
  function matmulrealDRArealD22(a,b) result(r)
    real(kind=RAdKind),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:,:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulrealDRArealD22
  function matmulrealDRAcomplexS22(a,b) result(r)
    real(kind=RAdKind),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulrealDRAcomplexS22
  function matmulrealDRAcomplexD22(a,b) result(r)
    real(kind=RAdKind),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulrealDRAcomplexD22
  function matmulcomplexSRArealS22(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulcomplexSRArealS22
  function matmulcomplexSRArealD22(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulcomplexSRArealD22
  function matmulcomplexSRAcomplexS22(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulcomplexSRAcomplexS22
  function matmulcomplexSRAcomplexD22(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulcomplexSRAcomplexD22
  function matmulcomplexDRArealS22(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulcomplexDRArealS22
  function matmulcomplexDRArealD22(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulcomplexDRArealD22
  function matmulcomplexDRAcomplexS22(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulcomplexDRAcomplexS22
  function matmulcomplexDRAcomplexD22(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1),lbound(b, 2) : ubound(b, 2))
    integer::j
    integer::k
    include 'RAmatmul22.i90'
  end function matmulcomplexDRAcomplexD22
  function matmulRArealSRArealS12(a,b) result(r)
    type(RArealS),intent(in)::a(:)
    type(RArealS),intent(in)::b(:,:)
    type(RArealS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealSRArealS12
  function matmulRArealSRArealD12(a,b) result(r)
    type(RArealS),intent(in)::a(:)
    type(RArealD),intent(in)::b(:,:)
    type(RArealD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealSRArealD12
  function matmulRArealSRAcomplexS12(a,b) result(r)
    type(RArealS),intent(in)::a(:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealSRAcomplexS12
  function matmulRArealSRAcomplexD12(a,b) result(r)
    type(RArealS),intent(in)::a(:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealSRAcomplexD12
  function matmulRArealDRArealS12(a,b) result(r)
    type(RArealD),intent(in)::a(:)
    type(RArealS),intent(in)::b(:,:)
    type(RArealD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealDRArealS12
  function matmulRArealDRArealD12(a,b) result(r)
    type(RArealD),intent(in)::a(:)
    type(RArealD),intent(in)::b(:,:)
    type(RArealD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealDRArealD12
  function matmulRArealDRAcomplexS12(a,b) result(r)
    type(RArealD),intent(in)::a(:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealDRAcomplexS12
  function matmulRArealDRAcomplexD12(a,b) result(r)
    type(RArealD),intent(in)::a(:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealDRAcomplexD12
  function matmulRAcomplexSRArealS12(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:)
    type(RArealS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexSRArealS12
  function matmulRAcomplexSRArealD12(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:)
    type(RArealD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexSRArealD12
  function matmulRAcomplexSRAcomplexS12(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexSRAcomplexS12
  function matmulRAcomplexSRAcomplexD12(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexSRAcomplexD12
  function matmulRAcomplexDRArealS12(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:)
    type(RArealS),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexDRArealS12
  function matmulRAcomplexDRArealD12(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:)
    type(RArealD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexDRArealD12
  function matmulRAcomplexDRAcomplexS12(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexDRAcomplexS12
  function matmulRAcomplexDRAcomplexD12(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexDRAcomplexD12
  function matmulRArealSinteger12(a,b) result(r)
    type(RArealS),intent(in)::a(:)
    integer,intent(in)::b(:,:)
    type(RArealS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealSinteger12
  function matmulRArealSrealS12(a,b) result(r)
    type(RArealS),intent(in)::a(:)
    real(kind=RAsKind),intent(in)::b(:,:)
    type(RArealS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealSrealS12
  function matmulRArealSrealD12(a,b) result(r)
    type(RArealS),intent(in)::a(:)
    real(kind=RAdKind),intent(in)::b(:,:)
    type(RArealD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealSrealD12
  function matmulRArealScomplexS12(a,b) result(r)
    type(RArealS),intent(in)::a(:)
    complex(kind=RAsKind),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealScomplexS12
  function matmulRArealScomplexD12(a,b) result(r)
    type(RArealS),intent(in)::a(:)
    complex(kind=RAdKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealScomplexD12
  function matmulRArealDinteger12(a,b) result(r)
    type(RArealD),intent(in)::a(:)
    integer,intent(in)::b(:,:)
    type(RArealD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealDinteger12
  function matmulRArealDrealS12(a,b) result(r)
    type(RArealD),intent(in)::a(:)
    real(kind=RAsKind),intent(in)::b(:,:)
    type(RArealD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealDrealS12
  function matmulRArealDrealD12(a,b) result(r)
    type(RArealD),intent(in)::a(:)
    real(kind=RAdKind),intent(in)::b(:,:)
    type(RArealD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealDrealD12
  function matmulRArealDcomplexS12(a,b) result(r)
    type(RArealD),intent(in)::a(:)
    complex(kind=RAsKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealDcomplexS12
  function matmulRArealDcomplexD12(a,b) result(r)
    type(RArealD),intent(in)::a(:)
    complex(kind=RAdKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRArealDcomplexD12
  function matmulRAcomplexSinteger12(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:)
    integer,intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexSinteger12
  function matmulRAcomplexSrealS12(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:)
    real(kind=RAsKind),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexSrealS12
  function matmulRAcomplexSrealD12(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:)
    real(kind=RAdKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexSrealD12
  function matmulRAcomplexScomplexS12(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:)
    complex(kind=RAsKind),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexScomplexS12
  function matmulRAcomplexScomplexD12(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:)
    complex(kind=RAdKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexScomplexD12
  function matmulRAcomplexDinteger12(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:)
    integer,intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexDinteger12
  function matmulRAcomplexDrealS12(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:)
    real(kind=RAsKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexDrealS12
  function matmulRAcomplexDrealD12(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:)
    real(kind=RAdKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexDrealD12
  function matmulRAcomplexDcomplexS12(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:)
    complex(kind=RAsKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexDcomplexS12
  function matmulRAcomplexDcomplexD12(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:)
    complex(kind=RAdKind),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulRAcomplexDcomplexD12
  function matmulintegerRArealS12(a,b) result(r)
    integer,intent(in)::a(:)
    type(RArealS),intent(in)::b(:,:)
    type(RArealS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulintegerRArealS12
  function matmulintegerRArealD12(a,b) result(r)
    integer,intent(in)::a(:)
    type(RArealD),intent(in)::b(:,:)
    type(RArealD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulintegerRArealD12
  function matmulintegerRAcomplexS12(a,b) result(r)
    integer,intent(in)::a(:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulintegerRAcomplexS12
  function matmulintegerRAcomplexD12(a,b) result(r)
    integer,intent(in)::a(:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulintegerRAcomplexD12
  function matmulrealSRArealS12(a,b) result(r)
    real(kind=RAsKind),intent(in)::a(:)
    type(RArealS),intent(in)::b(:,:)
    type(RArealS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulrealSRArealS12
  function matmulrealSRArealD12(a,b) result(r)
    real(kind=RAsKind),intent(in)::a(:)
    type(RArealD),intent(in)::b(:,:)
    type(RArealD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulrealSRArealD12
  function matmulrealSRAcomplexS12(a,b) result(r)
    real(kind=RAsKind),intent(in)::a(:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulrealSRAcomplexS12
  function matmulrealSRAcomplexD12(a,b) result(r)
    real(kind=RAsKind),intent(in)::a(:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulrealSRAcomplexD12
  function matmulrealDRArealS12(a,b) result(r)
    real(kind=RAdKind),intent(in)::a(:)
    type(RArealS),intent(in)::b(:,:)
    type(RArealD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulrealDRArealS12
  function matmulrealDRArealD12(a,b) result(r)
    real(kind=RAdKind),intent(in)::a(:)
    type(RArealD),intent(in)::b(:,:)
    type(RArealD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulrealDRArealD12
  function matmulrealDRAcomplexS12(a,b) result(r)
    real(kind=RAdKind),intent(in)::a(:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulrealDRAcomplexS12
  function matmulrealDRAcomplexD12(a,b) result(r)
    real(kind=RAdKind),intent(in)::a(:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulrealDRAcomplexD12
  function matmulcomplexSRArealS12(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a(:)
    type(RArealS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulcomplexSRArealS12
  function matmulcomplexSRArealD12(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a(:)
    type(RArealD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulcomplexSRArealD12
  function matmulcomplexSRAcomplexS12(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a(:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexS)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulcomplexSRAcomplexS12
  function matmulcomplexSRAcomplexD12(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a(:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulcomplexSRAcomplexD12
  function matmulcomplexDRArealS12(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a(:)
    type(RArealS),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulcomplexDRArealS12
  function matmulcomplexDRArealD12(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a(:)
    type(RArealD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulcomplexDRArealD12
  function matmulcomplexDRAcomplexS12(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a(:)
    type(RAcomplexS),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulcomplexDRAcomplexS12
  function matmulcomplexDRAcomplexD12(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a(:)
    type(RAcomplexD),intent(in)::b(:,:)
    type(RAcomplexD)::r(lbound(b, 2) : ubound(b, 2))
    integer::k
    include 'RAmatmul12.i90'
  end function matmulcomplexDRAcomplexD12
  function matmulRArealSRArealS21(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:)
    type(RArealS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealSRArealS21
  function matmulRArealSRArealD21(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealSRArealD21
  function matmulRArealSRAcomplexS21(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealSRAcomplexS21
  function matmulRArealSRAcomplexD21(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealSRAcomplexD21
  function matmulRArealDRArealS21(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealDRArealS21
  function matmulRArealDRArealD21(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealDRArealD21
  function matmulRArealDRAcomplexS21(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealDRAcomplexS21
  function matmulRArealDRAcomplexD21(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealDRAcomplexD21
  function matmulRAcomplexSRArealS21(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexSRArealS21
  function matmulRAcomplexSRArealD21(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexSRArealD21
  function matmulRAcomplexSRAcomplexS21(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexSRAcomplexS21
  function matmulRAcomplexSRAcomplexD21(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexSRAcomplexD21
  function matmulRAcomplexDRArealS21(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexDRArealS21
  function matmulRAcomplexDRArealD21(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexDRArealD21
  function matmulRAcomplexDRAcomplexS21(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexDRAcomplexS21
  function matmulRAcomplexDRAcomplexD21(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexDRAcomplexD21
  function matmulRArealSinteger21(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    integer,intent(in)::b(:)
    type(RArealS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealSinteger21
  function matmulRArealSrealS21(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    real(kind=RAsKind),intent(in)::b(:)
    type(RArealS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealSrealS21
  function matmulRArealSrealD21(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    real(kind=RAdKind),intent(in)::b(:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealSrealD21
  function matmulRArealScomplexS21(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    complex(kind=RAsKind),intent(in)::b(:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealScomplexS21
  function matmulRArealScomplexD21(a,b) result(r)
    type(RArealS),intent(in)::a(:,:)
    complex(kind=RAdKind),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealScomplexD21
  function matmulRArealDinteger21(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    integer,intent(in)::b(:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealDinteger21
  function matmulRArealDrealS21(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    real(kind=RAsKind),intent(in)::b(:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealDrealS21
  function matmulRArealDrealD21(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    real(kind=RAdKind),intent(in)::b(:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealDrealD21
  function matmulRArealDcomplexS21(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    complex(kind=RAsKind),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealDcomplexS21
  function matmulRArealDcomplexD21(a,b) result(r)
    type(RArealD),intent(in)::a(:,:)
    complex(kind=RAdKind),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRArealDcomplexD21
  function matmulRAcomplexSinteger21(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    integer,intent(in)::b(:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexSinteger21
  function matmulRAcomplexSrealS21(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    real(kind=RAsKind),intent(in)::b(:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexSrealS21
  function matmulRAcomplexSrealD21(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    real(kind=RAdKind),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexSrealD21
  function matmulRAcomplexScomplexS21(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    complex(kind=RAsKind),intent(in)::b(:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexScomplexS21
  function matmulRAcomplexScomplexD21(a,b) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    complex(kind=RAdKind),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexScomplexD21
  function matmulRAcomplexDinteger21(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    integer,intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexDinteger21
  function matmulRAcomplexDrealS21(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    real(kind=RAsKind),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexDrealS21
  function matmulRAcomplexDrealD21(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    real(kind=RAdKind),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexDrealD21
  function matmulRAcomplexDcomplexS21(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    complex(kind=RAsKind),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexDcomplexS21
  function matmulRAcomplexDcomplexD21(a,b) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    complex(kind=RAdKind),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulRAcomplexDcomplexD21
  function matmulintegerRArealS21(a,b) result(r)
    integer,intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:)
    type(RArealS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulintegerRArealS21
  function matmulintegerRArealD21(a,b) result(r)
    integer,intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulintegerRArealD21
  function matmulintegerRAcomplexS21(a,b) result(r)
    integer,intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulintegerRAcomplexS21
  function matmulintegerRAcomplexD21(a,b) result(r)
    integer,intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulintegerRAcomplexD21
  function matmulrealSRArealS21(a,b) result(r)
    real(kind=RAsKind),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:)
    type(RArealS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulrealSRArealS21
  function matmulrealSRArealD21(a,b) result(r)
    real(kind=RAsKind),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulrealSRArealD21
  function matmulrealSRAcomplexS21(a,b) result(r)
    real(kind=RAsKind),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulrealSRAcomplexS21
  function matmulrealSRAcomplexD21(a,b) result(r)
    real(kind=RAsKind),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulrealSRAcomplexD21
  function matmulrealDRArealS21(a,b) result(r)
    real(kind=RAdKind),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulrealDRArealS21
  function matmulrealDRArealD21(a,b) result(r)
    real(kind=RAdKind),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:)
    type(RArealD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulrealDRArealD21
  function matmulrealDRAcomplexS21(a,b) result(r)
    real(kind=RAdKind),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulrealDRAcomplexS21
  function matmulrealDRAcomplexD21(a,b) result(r)
    real(kind=RAdKind),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulrealDRAcomplexD21
  function matmulcomplexSRArealS21(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulcomplexSRArealS21
  function matmulcomplexSRArealD21(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulcomplexSRArealD21
  function matmulcomplexSRAcomplexS21(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:)
    type(RAcomplexS)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulcomplexSRAcomplexS21
  function matmulcomplexSRAcomplexD21(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulcomplexSRAcomplexD21
  function matmulcomplexDRArealS21(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a(:,:)
    type(RArealS),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulcomplexDRArealS21
  function matmulcomplexDRArealD21(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a(:,:)
    type(RArealD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulcomplexDRArealD21
  function matmulcomplexDRAcomplexS21(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a(:,:)
    type(RAcomplexS),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulcomplexDRAcomplexS21
  function matmulcomplexDRAcomplexD21(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a(:,:)
    type(RAcomplexD),intent(in)::b(:)
    type(RAcomplexD)::r(lbound(a, 1) : ubound(a, 1))
    integer::j
    include 'RAmatmul21.i90'
  end function matmulcomplexDRAcomplexD21
end module RAmatmul
