! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAmax
  use RAprec
  use RAtypes
  implicit none
  interface max
    module procedure maxRArealSRArealS
    module procedure maxRArealSRArealD
    module procedure maxRArealDRArealS
    module procedure maxRArealDRArealD
    module procedure maxRArealSinteger
    module procedure maxRArealSrealS
    module procedure maxRArealSrealD
    module procedure maxRArealDinteger
    module procedure maxRArealDrealS
    module procedure maxRArealDrealD
    module procedure maxintegerRArealS
    module procedure maxintegerRArealD
    module procedure maxrealSRArealS
    module procedure maxrealSRArealD
    module procedure maxrealDRArealS
    module procedure maxrealDRArealD
  end interface max
contains 
  elemental function maxRArealSRArealS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAmaxAA.i90'
  end function maxRArealSRArealS
  elemental function maxRArealSRArealD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAmaxAA.i90'
  end function maxRArealSRArealD
  elemental function maxRArealDRArealS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealD)::r
    include 'RAmaxAA.i90'
  end function maxRArealDRArealS
  elemental function maxRArealDRArealD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAmaxAA.i90'
  end function maxRArealDRArealD
  elemental function maxRArealSinteger(a,b) result(r)
    type(RArealS),intent(in)::a
    integer,intent(in)::b
    type(RArealS)::r
    include 'RAmaxAP.i90'
  end function maxRArealSinteger
  elemental function maxRArealSrealS(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealS)::r
    include 'RAmaxAP.i90'
  end function maxRArealSrealS
  elemental function maxRArealSrealD(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    include 'RAmaxAP.i90'
  end function maxRArealSrealD
  elemental function maxRArealDinteger(a,b) result(r)
    type(RArealD),intent(in)::a
    integer,intent(in)::b
    type(RArealD)::r
    include 'RAmaxAP.i90'
  end function maxRArealDinteger
  elemental function maxRArealDrealS(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealD)::r
    include 'RAmaxAP.i90'
  end function maxRArealDrealS
  elemental function maxRArealDrealD(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    include 'RAmaxAP.i90'
  end function maxRArealDrealD
  elemental function maxintegerRArealS(a,b) result(r)
    integer,intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAmaxPA.i90'
  end function maxintegerRArealS
  elemental function maxintegerRArealD(a,b) result(r)
    integer,intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAmaxPA.i90'
  end function maxintegerRArealD
  elemental function maxrealSRArealS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAmaxPA.i90'
  end function maxrealSRArealS
  elemental function maxrealSRArealD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAmaxPA.i90'
  end function maxrealSRArealD
  elemental function maxrealDRArealS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealD)::r
    include 'RAmaxPA.i90'
  end function maxrealDRArealS
  elemental function maxrealDRArealD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAmaxPA.i90'
  end function maxrealDRArealD
end module RAmax
