! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAmin
  use RAprec
  use RAtypes
  implicit none
  interface min
    module procedure minRArealSRArealS
    module procedure minRArealSRArealD
    module procedure minRArealDRArealS
    module procedure minRArealDRArealD
    module procedure minRArealSinteger
    module procedure minRArealSrealS
    module procedure minRArealSrealD
    module procedure minRArealDinteger
    module procedure minRArealDrealS
    module procedure minRArealDrealD
    module procedure minintegerRArealS
    module procedure minintegerRArealD
    module procedure minrealSRArealS
    module procedure minrealSRArealD
    module procedure minrealDRArealS
    module procedure minrealDRArealD
  end interface min
contains 
  elemental function minRArealSRArealS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAminAA.i90'
  end function minRArealSRArealS
  elemental function minRArealSRArealD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAminAA.i90'
  end function minRArealSRArealD
  elemental function minRArealDRArealS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealD)::r
    include 'RAminAA.i90'
  end function minRArealDRArealS
  elemental function minRArealDRArealD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAminAA.i90'
  end function minRArealDRArealD
  elemental function minRArealSinteger(a,b) result(r)
    type(RArealS),intent(in)::a
    integer,intent(in)::b
    type(RArealS)::r
    include 'RAminAP.i90'
  end function minRArealSinteger
  elemental function minRArealSrealS(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealS)::r
    include 'RAminAP.i90'
  end function minRArealSrealS
  elemental function minRArealSrealD(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    include 'RAminAP.i90'
  end function minRArealSrealD
  elemental function minRArealDinteger(a,b) result(r)
    type(RArealD),intent(in)::a
    integer,intent(in)::b
    type(RArealD)::r
    include 'RAminAP.i90'
  end function minRArealDinteger
  elemental function minRArealDrealS(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealD)::r
    include 'RAminAP.i90'
  end function minRArealDrealS
  elemental function minRArealDrealD(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    include 'RAminAP.i90'
  end function minRArealDrealD
  elemental function minintegerRArealS(a,b) result(r)
    integer,intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAminPA.i90'
  end function minintegerRArealS
  elemental function minintegerRArealD(a,b) result(r)
    integer,intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAminPA.i90'
  end function minintegerRArealD
  elemental function minrealSRArealS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAminPA.i90'
  end function minrealSRArealS
  elemental function minrealSRArealD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAminPA.i90'
  end function minrealSRArealD
  elemental function minrealDRArealS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealD)::r
    include 'RAminPA.i90'
  end function minrealDRArealS
  elemental function minrealDRArealD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAminPA.i90'
  end function minrealDRArealD
end module RAmin
