! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAmult
  use RAprec
  use RAtypes
  implicit none
  interface operator(*)
    module procedure multRArealSRArealS
    module procedure multRArealSRArealD
    module procedure multRArealSRAcomplexS
    module procedure multRArealSRAcomplexD
    module procedure multRArealDRArealS
    module procedure multRArealDRArealD
    module procedure multRArealDRAcomplexS
    module procedure multRArealDRAcomplexD
    module procedure multRAcomplexSRArealS
    module procedure multRAcomplexSRArealD
    module procedure multRAcomplexSRAcomplexS
    module procedure multRAcomplexSRAcomplexD
    module procedure multRAcomplexDRArealS
    module procedure multRAcomplexDRArealD
    module procedure multRAcomplexDRAcomplexS
    module procedure multRAcomplexDRAcomplexD
    module procedure multRArealSinteger
    module procedure multRArealSrealS
    module procedure multRArealSrealD
    module procedure multRArealScomplexS
    module procedure multRArealScomplexD
    module procedure multRArealDinteger
    module procedure multRArealDrealS
    module procedure multRArealDrealD
    module procedure multRArealDcomplexS
    module procedure multRArealDcomplexD
    module procedure multRAcomplexSinteger
    module procedure multRAcomplexSrealS
    module procedure multRAcomplexSrealD
    module procedure multRAcomplexScomplexS
    module procedure multRAcomplexScomplexD
    module procedure multRAcomplexDinteger
    module procedure multRAcomplexDrealS
    module procedure multRAcomplexDrealD
    module procedure multRAcomplexDcomplexS
    module procedure multRAcomplexDcomplexD
    module procedure multintegerRArealS
    module procedure multintegerRArealD
    module procedure multintegerRAcomplexS
    module procedure multintegerRAcomplexD
    module procedure multrealSRArealS
    module procedure multrealSRArealD
    module procedure multrealSRAcomplexS
    module procedure multrealSRAcomplexD
    module procedure multrealDRArealS
    module procedure multrealDRArealD
    module procedure multrealDRAcomplexS
    module procedure multrealDRAcomplexD
    module procedure multcomplexSRArealS
    module procedure multcomplexSRArealD
    module procedure multcomplexSRAcomplexS
    module procedure multcomplexSRAcomplexD
    module procedure multcomplexDRArealS
    module procedure multcomplexDRArealD
    module procedure multcomplexDRAcomplexS
    module procedure multcomplexDRAcomplexD
  end interface 
contains 
  elemental function multRArealSRArealS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAmultAA.i90'
  end function multRArealSRArealS
  elemental function multRArealSRArealD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAmultAA.i90'
  end function multRArealSRArealD
  elemental function multRArealSRAcomplexS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAmultAA.i90'
  end function multRArealSRAcomplexS
  elemental function multRArealSRAcomplexD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAA.i90'
  end function multRArealSRAcomplexD
  elemental function multRArealDRArealS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealD)::r
    include 'RAmultAA.i90'
  end function multRArealDRArealS
  elemental function multRArealDRArealD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAmultAA.i90'
  end function multRArealDRArealD
  elemental function multRArealDRAcomplexS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAA.i90'
  end function multRArealDRAcomplexS
  elemental function multRArealDRAcomplexD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAA.i90'
  end function multRArealDRAcomplexD
  elemental function multRAcomplexSRArealS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAmultAA.i90'
  end function multRAcomplexSRArealS
  elemental function multRAcomplexSRArealD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAA.i90'
  end function multRAcomplexSRArealD
  elemental function multRAcomplexSRAcomplexS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAmultAA.i90'
  end function multRAcomplexSRAcomplexS
  elemental function multRAcomplexSRAcomplexD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAA.i90'
  end function multRAcomplexSRAcomplexD
  elemental function multRAcomplexDRArealS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAA.i90'
  end function multRAcomplexDRArealS
  elemental function multRAcomplexDRArealD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAA.i90'
  end function multRAcomplexDRArealD
  elemental function multRAcomplexDRAcomplexS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAA.i90'
  end function multRAcomplexDRAcomplexS
  elemental function multRAcomplexDRAcomplexD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAA.i90'
  end function multRAcomplexDRAcomplexD
  elemental function multRArealSinteger(a,b) result(r)
    type(RArealS),intent(in)::a
    integer,intent(in)::b
    type(RArealS)::r
    include 'RAmultAP.i90'
  end function multRArealSinteger
  elemental function multRArealSrealS(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealS)::r
    include 'RAmultAP.i90'
  end function multRArealSrealS
  elemental function multRArealSrealD(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    include 'RAmultAP.i90'
  end function multRArealSrealD
  elemental function multRArealScomplexS(a,b) result(r)
    type(RArealS),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexS)::r
    include 'RAmultAP.i90'
  end function multRArealScomplexS
  elemental function multRArealScomplexD(a,b) result(r)
    type(RArealS),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAP.i90'
  end function multRArealScomplexD
  elemental function multRArealDinteger(a,b) result(r)
    type(RArealD),intent(in)::a
    integer,intent(in)::b
    type(RArealD)::r
    include 'RAmultAP.i90'
  end function multRArealDinteger
  elemental function multRArealDrealS(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealD)::r
    include 'RAmultAP.i90'
  end function multRArealDrealS
  elemental function multRArealDrealD(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    include 'RAmultAP.i90'
  end function multRArealDrealD
  elemental function multRArealDcomplexS(a,b) result(r)
    type(RArealD),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAP.i90'
  end function multRArealDcomplexS
  elemental function multRArealDcomplexD(a,b) result(r)
    type(RArealD),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAP.i90'
  end function multRArealDcomplexD
  elemental function multRAcomplexSinteger(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    integer,intent(in)::b
    type(RAcomplexS)::r
    include 'RAmultAP.i90'
  end function multRAcomplexSinteger
  elemental function multRAcomplexSrealS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RAcomplexS)::r
    include 'RAmultAP.i90'
  end function multRAcomplexSrealS
  elemental function multRAcomplexSrealD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAP.i90'
  end function multRAcomplexSrealD
  elemental function multRAcomplexScomplexS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexS)::r
    include 'RAmultAP.i90'
  end function multRAcomplexScomplexS
  elemental function multRAcomplexScomplexD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAP.i90'
  end function multRAcomplexScomplexD
  elemental function multRAcomplexDinteger(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    integer,intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAP.i90'
  end function multRAcomplexDinteger
  elemental function multRAcomplexDrealS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAP.i90'
  end function multRAcomplexDrealS
  elemental function multRAcomplexDrealD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAP.i90'
  end function multRAcomplexDrealD
  elemental function multRAcomplexDcomplexS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAP.i90'
  end function multRAcomplexDcomplexS
  elemental function multRAcomplexDcomplexD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultAP.i90'
  end function multRAcomplexDcomplexD
  elemental function multintegerRArealS(a,b) result(r)
    integer,intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAmultPA.i90'
  end function multintegerRArealS
  elemental function multintegerRArealD(a,b) result(r)
    integer,intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAmultPA.i90'
  end function multintegerRArealD
  elemental function multintegerRAcomplexS(a,b) result(r)
    integer,intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAmultPA.i90'
  end function multintegerRAcomplexS
  elemental function multintegerRAcomplexD(a,b) result(r)
    integer,intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultPA.i90'
  end function multintegerRAcomplexD
  elemental function multrealSRArealS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAmultPA.i90'
  end function multrealSRArealS
  elemental function multrealSRArealD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAmultPA.i90'
  end function multrealSRArealD
  elemental function multrealSRAcomplexS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAmultPA.i90'
  end function multrealSRAcomplexS
  elemental function multrealSRAcomplexD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultPA.i90'
  end function multrealSRAcomplexD
  elemental function multrealDRArealS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealD)::r
    include 'RAmultPA.i90'
  end function multrealDRArealS
  elemental function multrealDRArealD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAmultPA.i90'
  end function multrealDRArealD
  elemental function multrealDRAcomplexS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultPA.i90'
  end function multrealDRAcomplexS
  elemental function multrealDRAcomplexD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultPA.i90'
  end function multrealDRAcomplexD
  elemental function multcomplexSRArealS(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAmultPA.i90'
  end function multcomplexSRArealS
  elemental function multcomplexSRArealD(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultPA.i90'
  end function multcomplexSRArealD
  elemental function multcomplexSRAcomplexS(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAmultPA.i90'
  end function multcomplexSRAcomplexS
  elemental function multcomplexSRAcomplexD(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultPA.i90'
  end function multcomplexSRAcomplexD
  elemental function multcomplexDRArealS(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultPA.i90'
  end function multcomplexDRArealS
  elemental function multcomplexDRArealD(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultPA.i90'
  end function multcomplexDRArealD
  elemental function multcomplexDRAcomplexS(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultPA.i90'
  end function multcomplexDRAcomplexS
  elemental function multcomplexDRAcomplexD(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAmultPA.i90'
  end function multcomplexDRAcomplexD
end module RAmult
