! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAne
  use RAprec
  use RAtypes
  implicit none
  interface operator(/=)
    module procedure neRArealSRArealS
    module procedure neRArealSRArealD
    module procedure neRArealSRAcomplexS
    module procedure neRArealSRAcomplexD
    module procedure neRArealDRArealS
    module procedure neRArealDRArealD
    module procedure neRArealDRAcomplexS
    module procedure neRArealDRAcomplexD
    module procedure neRAcomplexSRArealS
    module procedure neRAcomplexSRArealD
    module procedure neRAcomplexSRAcomplexS
    module procedure neRAcomplexSRAcomplexD
    module procedure neRAcomplexDRArealS
    module procedure neRAcomplexDRArealD
    module procedure neRAcomplexDRAcomplexS
    module procedure neRAcomplexDRAcomplexD
    module procedure neRArealSinteger
    module procedure neRArealSrealS
    module procedure neRArealSrealD
    module procedure neRArealScomplexS
    module procedure neRArealScomplexD
    module procedure neRArealDinteger
    module procedure neRArealDrealS
    module procedure neRArealDrealD
    module procedure neRArealDcomplexS
    module procedure neRArealDcomplexD
    module procedure neRAcomplexSinteger
    module procedure neRAcomplexSrealS
    module procedure neRAcomplexSrealD
    module procedure neRAcomplexScomplexS
    module procedure neRAcomplexScomplexD
    module procedure neRAcomplexDinteger
    module procedure neRAcomplexDrealS
    module procedure neRAcomplexDrealD
    module procedure neRAcomplexDcomplexS
    module procedure neRAcomplexDcomplexD
    module procedure neintegerRArealS
    module procedure neintegerRArealD
    module procedure neintegerRAcomplexS
    module procedure neintegerRAcomplexD
    module procedure nerealSRArealS
    module procedure nerealSRArealD
    module procedure nerealSRAcomplexS
    module procedure nerealSRAcomplexD
    module procedure nerealDRArealS
    module procedure nerealDRArealD
    module procedure nerealDRAcomplexS
    module procedure nerealDRAcomplexD
    module procedure necomplexSRArealS
    module procedure necomplexSRArealD
    module procedure necomplexSRAcomplexS
    module procedure necomplexSRAcomplexD
    module procedure necomplexDRArealS
    module procedure necomplexDRArealD
    module procedure necomplexDRAcomplexS
    module procedure necomplexDRAcomplexD
  end interface 
contains 
  elemental function neRArealSRArealS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRArealSRArealS
  elemental function neRArealSRArealD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRArealSRArealD
  elemental function neRArealSRAcomplexS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRArealSRAcomplexS
  elemental function neRArealSRAcomplexD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRArealSRAcomplexD
  elemental function neRArealDRArealS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRArealDRArealS
  elemental function neRArealDRArealD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRArealDRArealD
  elemental function neRArealDRAcomplexS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRArealDRAcomplexS
  elemental function neRArealDRAcomplexD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRArealDRAcomplexD
  elemental function neRAcomplexSRArealS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRAcomplexSRArealS
  elemental function neRAcomplexSRArealD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRAcomplexSRArealD
  elemental function neRAcomplexSRAcomplexS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRAcomplexSRAcomplexS
  elemental function neRAcomplexSRAcomplexD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRAcomplexSRAcomplexD
  elemental function neRAcomplexDRArealS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRAcomplexDRArealS
  elemental function neRAcomplexDRArealD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRAcomplexDRArealD
  elemental function neRAcomplexDRAcomplexS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRAcomplexDRAcomplexS
  elemental function neRAcomplexDRAcomplexD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAneAA.i90'
  end function neRAcomplexDRAcomplexD
  elemental function neRArealSinteger(a,b) result(r)
    type(RArealS),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRArealSinteger
  elemental function neRArealSrealS(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRArealSrealS
  elemental function neRArealSrealD(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRArealSrealD
  elemental function neRArealScomplexS(a,b) result(r)
    type(RArealS),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRArealScomplexS
  elemental function neRArealScomplexD(a,b) result(r)
    type(RArealS),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRArealScomplexD
  elemental function neRArealDinteger(a,b) result(r)
    type(RArealD),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRArealDinteger
  elemental function neRArealDrealS(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRArealDrealS
  elemental function neRArealDrealD(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRArealDrealD
  elemental function neRArealDcomplexS(a,b) result(r)
    type(RArealD),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRArealDcomplexS
  elemental function neRArealDcomplexD(a,b) result(r)
    type(RArealD),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRArealDcomplexD
  elemental function neRAcomplexSinteger(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRAcomplexSinteger
  elemental function neRAcomplexSrealS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRAcomplexSrealS
  elemental function neRAcomplexSrealD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRAcomplexSrealD
  elemental function neRAcomplexScomplexS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRAcomplexScomplexS
  elemental function neRAcomplexScomplexD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRAcomplexScomplexD
  elemental function neRAcomplexDinteger(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    integer,intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRAcomplexDinteger
  elemental function neRAcomplexDrealS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRAcomplexDrealS
  elemental function neRAcomplexDrealD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRAcomplexDrealD
  elemental function neRAcomplexDcomplexS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRAcomplexDcomplexS
  elemental function neRAcomplexDcomplexD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    logical::r
    include 'RAneAP.i90'
  end function neRAcomplexDcomplexD
  elemental function neintegerRArealS(a,b) result(r)
    integer,intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function neintegerRArealS
  elemental function neintegerRArealD(a,b) result(r)
    integer,intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function neintegerRArealD
  elemental function neintegerRAcomplexS(a,b) result(r)
    integer,intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function neintegerRAcomplexS
  elemental function neintegerRAcomplexD(a,b) result(r)
    integer,intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function neintegerRAcomplexD
  elemental function nerealSRArealS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function nerealSRArealS
  elemental function nerealSRArealD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function nerealSRArealD
  elemental function nerealSRAcomplexS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function nerealSRAcomplexS
  elemental function nerealSRAcomplexD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function nerealSRAcomplexD
  elemental function nerealDRArealS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function nerealDRArealS
  elemental function nerealDRArealD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function nerealDRArealD
  elemental function nerealDRAcomplexS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function nerealDRAcomplexS
  elemental function nerealDRAcomplexD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function nerealDRAcomplexD
  elemental function necomplexSRArealS(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function necomplexSRArealS
  elemental function necomplexSRArealD(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function necomplexSRArealD
  elemental function necomplexSRAcomplexS(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function necomplexSRAcomplexS
  elemental function necomplexSRAcomplexD(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function necomplexSRAcomplexD
  elemental function necomplexDRArealS(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function necomplexDRArealS
  elemental function necomplexDRArealD(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function necomplexDRArealD
  elemental function necomplexDRAcomplexS(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function necomplexDRAcomplexS
  elemental function necomplexDRAcomplexD(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    logical::r
    include 'RAnePA.i90'
  end function necomplexDRAcomplexD
end module RAne
