! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RApow
  use RAprec
  use RAtypes
  use RAmult
  use RAlog
  use RAexp
  implicit none
  interface operator(**)
    module procedure powRArealSRArealS
    module procedure powRArealSRArealD
    module procedure powRArealSRAcomplexS
    module procedure powRArealSRAcomplexD
    module procedure powRArealDRArealS
    module procedure powRArealDRArealD
    module procedure powRArealDRAcomplexS
    module procedure powRArealDRAcomplexD
    module procedure powRAcomplexSRArealS
    module procedure powRAcomplexSRArealD
    module procedure powRAcomplexSRAcomplexS
    module procedure powRAcomplexSRAcomplexD
    module procedure powRAcomplexDRArealS
    module procedure powRAcomplexDRArealD
    module procedure powRAcomplexDRAcomplexS
    module procedure powRAcomplexDRAcomplexD
    module procedure powRArealSinteger
    module procedure powRArealSrealS
    module procedure powRArealSrealD
    module procedure powRArealScomplexS
    module procedure powRArealScomplexD
    module procedure powRArealDinteger
    module procedure powRArealDrealS
    module procedure powRArealDrealD
    module procedure powRArealDcomplexS
    module procedure powRArealDcomplexD
    module procedure powRAcomplexSinteger
    module procedure powRAcomplexSrealS
    module procedure powRAcomplexSrealD
    module procedure powRAcomplexScomplexS
    module procedure powRAcomplexScomplexD
    module procedure powRAcomplexDinteger
    module procedure powRAcomplexDrealS
    module procedure powRAcomplexDrealD
    module procedure powRAcomplexDcomplexS
    module procedure powRAcomplexDcomplexD
    module procedure powintegerRArealS
    module procedure powintegerRArealD
    module procedure powintegerRAcomplexS
    module procedure powintegerRAcomplexD
    module procedure powrealSRArealS
    module procedure powrealSRArealD
    module procedure powrealSRAcomplexS
    module procedure powrealSRAcomplexD
    module procedure powrealDRArealS
    module procedure powrealDRArealD
    module procedure powrealDRAcomplexS
    module procedure powrealDRAcomplexD
    module procedure powcomplexSRArealS
    module procedure powcomplexSRArealD
    module procedure powcomplexSRAcomplexS
    module procedure powcomplexSRAcomplexD
    module procedure powcomplexDRArealS
    module procedure powcomplexDRArealD
    module procedure powcomplexDRAcomplexS
    module procedure powcomplexDRAcomplexD
  end interface 
contains 
  elemental function powRArealSRArealS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RApowAA.i90'
  end function powRArealSRArealS
  elemental function powRArealSRArealD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RApowAA.i90'
  end function powRArealSRArealD
  elemental function powRArealSRAcomplexS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RApowAA.i90'
  end function powRArealSRAcomplexS
  elemental function powRArealSRAcomplexD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowAA.i90'
  end function powRArealSRAcomplexD
  elemental function powRArealDRArealS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealD)::r
    include 'RApowAA.i90'
  end function powRArealDRArealS
  elemental function powRArealDRArealD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RApowAA.i90'
  end function powRArealDRArealD
  elemental function powRArealDRAcomplexS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowAA.i90'
  end function powRArealDRAcomplexS
  elemental function powRArealDRAcomplexD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowAA.i90'
  end function powRArealDRAcomplexD
  elemental function powRAcomplexSRArealS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexS)::r
    include 'RApowAA.i90'
  end function powRAcomplexSRArealS
  elemental function powRAcomplexSRArealD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowAA.i90'
  end function powRAcomplexSRArealD
  elemental function powRAcomplexSRAcomplexS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RApowAA.i90'
  end function powRAcomplexSRAcomplexS
  elemental function powRAcomplexSRAcomplexD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowAA.i90'
  end function powRAcomplexSRAcomplexD
  elemental function powRAcomplexDRArealS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowAA.i90'
  end function powRAcomplexDRArealS
  elemental function powRAcomplexDRArealD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowAA.i90'
  end function powRAcomplexDRArealD
  elemental function powRAcomplexDRAcomplexS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowAA.i90'
  end function powRAcomplexDRAcomplexS
  elemental function powRAcomplexDRAcomplexD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowAA.i90'
  end function powRAcomplexDRAcomplexD
  elemental function powRArealSinteger(a,b) result(r)
    type(RArealS),intent(in)::a
    integer,intent(in)::b
    type(RArealS)::r
    real(kind=RAsKind)::recip
    type(RArealS)::s
    type(RArealS)::t
    integer::j
    real::expDiff
    include 'RApowAPi.i90'
  end function powRArealSinteger
  elemental function powRArealSrealS(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealS)::r
    real(kind=RAsKind)::recip
    type(RArealS)::s
    type(RArealS)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRArealSrealS
  elemental function powRArealSrealD(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    real(kind=RAdKind)::recip
    type(RArealD)::s
    type(RArealD)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRArealSrealD
  elemental function powRArealScomplexS(a,b) result(r)
    type(RArealS),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexS)::r
    complex(kind=RAsKind)::recip
    type(RAcomplexS)::s
    type(RAcomplexS)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRArealScomplexS
  elemental function powRArealScomplexD(a,b) result(r)
    type(RArealS),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    complex(kind=RAdKind)::recip
    type(RAcomplexD)::s
    type(RAcomplexD)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRArealScomplexD
  elemental function powRArealDinteger(a,b) result(r)
    type(RArealD),intent(in)::a
    integer,intent(in)::b
    type(RArealD)::r
    real(kind=RAdKind)::recip
    type(RArealD)::s
    type(RArealD)::t
    integer::j
    real::expDiff
    include 'RApowAPi.i90'
  end function powRArealDinteger
  elemental function powRArealDrealS(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealD)::r
    real(kind=RAdKind)::recip
    type(RArealD)::s
    type(RArealD)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRArealDrealS
  elemental function powRArealDrealD(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    real(kind=RAdKind)::recip
    type(RArealD)::s
    type(RArealD)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRArealDrealD
  elemental function powRArealDcomplexS(a,b) result(r)
    type(RArealD),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexD)::r
    complex(kind=RAdKind)::recip
    type(RAcomplexD)::s
    type(RAcomplexD)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRArealDcomplexS
  elemental function powRArealDcomplexD(a,b) result(r)
    type(RArealD),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    complex(kind=RAdKind)::recip
    type(RAcomplexD)::s
    type(RAcomplexD)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRArealDcomplexD
  elemental function powRAcomplexSinteger(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    integer,intent(in)::b
    type(RAcomplexS)::r
    complex(kind=RAsKind)::recip
    type(RAcomplexS)::s
    type(RAcomplexS)::t
    integer::j
    real::expDiff
    include 'RApowAPi.i90'
  end function powRAcomplexSinteger
  elemental function powRAcomplexSrealS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RAcomplexS)::r
    complex(kind=RAsKind)::recip
    type(RAcomplexS)::s
    type(RAcomplexS)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRAcomplexSrealS
  elemental function powRAcomplexSrealD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    complex(kind=RAdKind)::recip
    type(RAcomplexD)::s
    type(RAcomplexD)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRAcomplexSrealD
  elemental function powRAcomplexScomplexS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexS)::r
    complex(kind=RAsKind)::recip
    type(RAcomplexS)::s
    type(RAcomplexS)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRAcomplexScomplexS
  elemental function powRAcomplexScomplexD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    complex(kind=RAdKind)::recip
    type(RAcomplexD)::s
    type(RAcomplexD)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRAcomplexScomplexD
  elemental function powRAcomplexDinteger(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    integer,intent(in)::b
    type(RAcomplexD)::r
    complex(kind=RAdKind)::recip
    type(RAcomplexD)::s
    type(RAcomplexD)::t
    integer::j
    real::expDiff
    include 'RApowAPi.i90'
  end function powRAcomplexDinteger
  elemental function powRAcomplexDrealS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RAcomplexD)::r
    complex(kind=RAdKind)::recip
    type(RAcomplexD)::s
    type(RAcomplexD)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRAcomplexDrealS
  elemental function powRAcomplexDrealD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    complex(kind=RAdKind)::recip
    type(RAcomplexD)::s
    type(RAcomplexD)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRAcomplexDrealD
  elemental function powRAcomplexDcomplexS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexD)::r
    complex(kind=RAdKind)::recip
    type(RAcomplexD)::s
    type(RAcomplexD)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRAcomplexDcomplexS
  elemental function powRAcomplexDcomplexD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    complex(kind=RAdKind)::recip
    type(RAcomplexD)::s
    type(RAcomplexD)::t
    integer::j
    real::expDiff
    include 'RApowAP.i90'
  end function powRAcomplexDcomplexD
  elemental function powintegerRArealS(a,b) result(r)
    integer,intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RApowPiA.i90'
  end function powintegerRArealS
  elemental function powintegerRArealD(a,b) result(r)
    integer,intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RApowPiA.i90'
  end function powintegerRArealD
  elemental function powintegerRAcomplexS(a,b) result(r)
    integer,intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RApowPiA.i90'
  end function powintegerRAcomplexS
  elemental function powintegerRAcomplexD(a,b) result(r)
    integer,intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowPiA.i90'
  end function powintegerRAcomplexD
  elemental function powrealSRArealS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RApowPA.i90'
  end function powrealSRArealS
  elemental function powrealSRArealD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RApowPA.i90'
  end function powrealSRArealD
  elemental function powrealSRAcomplexS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RApowPA.i90'
  end function powrealSRAcomplexS
  elemental function powrealSRAcomplexD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowPA.i90'
  end function powrealSRAcomplexD
  elemental function powrealDRArealS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealD)::r
    include 'RApowPA.i90'
  end function powrealDRArealS
  elemental function powrealDRArealD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RApowPA.i90'
  end function powrealDRArealD
  elemental function powrealDRAcomplexS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowPA.i90'
  end function powrealDRAcomplexS
  elemental function powrealDRAcomplexD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowPA.i90'
  end function powrealDRAcomplexD
  elemental function powcomplexSRArealS(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexS)::r
    include 'RApowPA.i90'
  end function powcomplexSRArealS
  elemental function powcomplexSRArealD(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowPA.i90'
  end function powcomplexSRArealD
  elemental function powcomplexSRAcomplexS(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RApowPA.i90'
  end function powcomplexSRAcomplexS
  elemental function powcomplexSRAcomplexD(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowPA.i90'
  end function powcomplexSRAcomplexD
  elemental function powcomplexDRArealS(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowPA.i90'
  end function powcomplexDRArealS
  elemental function powcomplexDRArealD(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowPA.i90'
  end function powcomplexDRArealD
  elemental function powcomplexDRAcomplexS(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowPA.i90'
  end function powcomplexDRAcomplexS
  elemental function powcomplexDRAcomplexD(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RApowPA.i90'
  end function powcomplexDRAcomplexD
end module RApow
