! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAprec
  implicit none
  integer,public,parameter::RAsKind = kind(1.0)
  integer,public,parameter::RAdKind = kind(1.0D0)
end module RAprec
