! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAsign
  use RAprec
  use RAtypes
  use RAabs
  use RAasgn
  use RAmult
  implicit none
  interface sign
    module procedure signRArealSRArealS
    module procedure signRArealDRArealD
    module procedure signRArealSrealS
    module procedure signRArealDrealD
    module procedure signrealSRArealS
    module procedure signrealDRArealD
  end interface sign
contains 
  elemental function signRArealSRArealS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    real(kind=RAsKind)::one
    include 'RAsignAA.i90'
  end function signRArealSRArealS
  elemental function signRArealDRArealD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    real(kind=RAdKind)::one
    include 'RAsignAA.i90'
  end function signRArealDRArealD
  elemental function signRArealSrealS(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealS)::r
    real(kind=RAsKind)::one
    include 'RAsignAP.i90'
  end function signRArealSrealS
  elemental function signRArealDrealD(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    real(kind=RAdKind)::one
    include 'RAsignAP.i90'
  end function signRArealDrealD
  elemental function signrealSRArealS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    real(kind=RAsKind)::r
    real(kind=RAsKind)::one
    include 'RAsignPA.i90'
  end function signrealSRArealS
  elemental function signrealDRArealD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    real(kind=RAdKind)::r
    real(kind=RAdKind)::one
    include 'RAsignPA.i90'
  end function signrealDRArealD
end module RAsign
