! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAsin
  use RAprec
  use RAtypes
  implicit none
  interface sin
    module procedure sinRArealS
    module procedure sinRArealD
    module procedure sinRAcomplexS
    module procedure sinRAcomplexD
  end interface sin
contains 
  elemental function sinRArealS(a) result(s)
    type(RArealS),intent(in)::a
    type(RArealS)::s
    type(RArealS)::c
    type(RArealS)::t
    include 'RAsincos.i90'
  end function sinRArealS
  elemental function sinRArealD(a) result(s)
    type(RArealD),intent(in)::a
    type(RArealD)::s
    type(RArealD)::c
    type(RArealD)::t
    include 'RAsincos.i90'
  end function sinRArealD
  elemental function sinRAcomplexS(a) result(s)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexS)::s
    type(RAcomplexS)::c
    type(RAcomplexS)::t
    include 'RAsincos.i90'
  end function sinRAcomplexS
  elemental function sinRAcomplexD(a) result(s)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexD)::s
    type(RAcomplexD)::c
    type(RAcomplexD)::t
    include 'RAsincos.i90'
  end function sinRAcomplexD
end module RAsin
