! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAsinh
  use RAprec
  use RAtypes
  implicit none
  interface sinh
    module procedure sinhRArealS
    module procedure sinhRArealD
  end interface sinh
contains 
  elemental function sinhRArealS(a) result(s)
    type(RArealS),intent(in)::a
    type(RArealS)::s
    type(RArealS)::c
    type(RArealS)::t
    include 'RAsinhcosh.i90'
  end function sinhRArealS
  elemental function sinhRArealD(a) result(s)
    type(RArealD),intent(in)::a
    type(RArealD)::s
    type(RArealD)::c
    type(RArealD)::t
    include 'RAsinhcosh.i90'
  end function sinhRArealD
end module RAsinh
