! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAsub
  use RAprec
  use RAtypes
  implicit none
  interface operator(-)
    module procedure subRArealSRArealS
    module procedure subRArealSRArealD
    module procedure subRArealSRAcomplexS
    module procedure subRArealSRAcomplexD
    module procedure subRArealDRArealS
    module procedure subRArealDRArealD
    module procedure subRArealDRAcomplexS
    module procedure subRArealDRAcomplexD
    module procedure subRAcomplexSRArealS
    module procedure subRAcomplexSRArealD
    module procedure subRAcomplexSRAcomplexS
    module procedure subRAcomplexSRAcomplexD
    module procedure subRAcomplexDRArealS
    module procedure subRAcomplexDRArealD
    module procedure subRAcomplexDRAcomplexS
    module procedure subRAcomplexDRAcomplexD
    module procedure subRArealSinteger
    module procedure subRArealSrealS
    module procedure subRArealSrealD
    module procedure subRArealScomplexS
    module procedure subRArealScomplexD
    module procedure subRArealDinteger
    module procedure subRArealDrealS
    module procedure subRArealDrealD
    module procedure subRArealDcomplexS
    module procedure subRArealDcomplexD
    module procedure subRAcomplexSinteger
    module procedure subRAcomplexSrealS
    module procedure subRAcomplexSrealD
    module procedure subRAcomplexScomplexS
    module procedure subRAcomplexScomplexD
    module procedure subRAcomplexDinteger
    module procedure subRAcomplexDrealS
    module procedure subRAcomplexDrealD
    module procedure subRAcomplexDcomplexS
    module procedure subRAcomplexDcomplexD
    module procedure subintegerRArealS
    module procedure subintegerRArealD
    module procedure subintegerRAcomplexS
    module procedure subintegerRAcomplexD
    module procedure subrealSRArealS
    module procedure subrealSRArealD
    module procedure subrealSRAcomplexS
    module procedure subrealSRAcomplexD
    module procedure subrealDRArealS
    module procedure subrealDRArealD
    module procedure subrealDRAcomplexS
    module procedure subrealDRAcomplexD
    module procedure subcomplexSRArealS
    module procedure subcomplexSRArealD
    module procedure subcomplexSRAcomplexS
    module procedure subcomplexSRAcomplexD
    module procedure subcomplexDRArealS
    module procedure subcomplexDRArealD
    module procedure subcomplexDRAcomplexS
    module procedure subcomplexDRAcomplexD
  end interface 
contains 
  elemental function subRArealSRArealS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAsubAA.i90'
  end function subRArealSRArealS
  elemental function subRArealSRArealD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAsubAA.i90'
  end function subRArealSRArealD
  elemental function subRArealSRAcomplexS(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAsubAA.i90'
  end function subRArealSRAcomplexS
  elemental function subRArealSRAcomplexD(a,b) result(r)
    type(RArealS),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAA.i90'
  end function subRArealSRAcomplexD
  elemental function subRArealDRArealS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealD)::r
    include 'RAsubAA.i90'
  end function subRArealDRArealS
  elemental function subRArealDRArealD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAsubAA.i90'
  end function subRArealDRArealD
  elemental function subRArealDRAcomplexS(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAA.i90'
  end function subRArealDRAcomplexS
  elemental function subRArealDRAcomplexD(a,b) result(r)
    type(RArealD),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAA.i90'
  end function subRArealDRAcomplexD
  elemental function subRAcomplexSRArealS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAsubAA.i90'
  end function subRAcomplexSRArealS
  elemental function subRAcomplexSRArealD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAA.i90'
  end function subRAcomplexSRArealD
  elemental function subRAcomplexSRAcomplexS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAsubAA.i90'
  end function subRAcomplexSRAcomplexS
  elemental function subRAcomplexSRAcomplexD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAA.i90'
  end function subRAcomplexSRAcomplexD
  elemental function subRAcomplexDRArealS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAA.i90'
  end function subRAcomplexDRArealS
  elemental function subRAcomplexDRArealD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAA.i90'
  end function subRAcomplexDRArealD
  elemental function subRAcomplexDRAcomplexS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAA.i90'
  end function subRAcomplexDRAcomplexS
  elemental function subRAcomplexDRAcomplexD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAA.i90'
  end function subRAcomplexDRAcomplexD
  elemental function subRArealSinteger(a,b) result(r)
    type(RArealS),intent(in)::a
    integer,intent(in)::b
    type(RArealS)::r
    include 'RAsubAP.i90'
  end function subRArealSinteger
  elemental function subRArealSrealS(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealS)::r
    include 'RAsubAP.i90'
  end function subRArealSrealS
  elemental function subRArealSrealD(a,b) result(r)
    type(RArealS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    include 'RAsubAP.i90'
  end function subRArealSrealD
  elemental function subRArealScomplexS(a,b) result(r)
    type(RArealS),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexS)::r
    include 'RAsubAP.i90'
  end function subRArealScomplexS
  elemental function subRArealScomplexD(a,b) result(r)
    type(RArealS),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAP.i90'
  end function subRArealScomplexD
  elemental function subRArealDinteger(a,b) result(r)
    type(RArealD),intent(in)::a
    integer,intent(in)::b
    type(RArealD)::r
    include 'RAsubAP.i90'
  end function subRArealDinteger
  elemental function subRArealDrealS(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RArealD)::r
    include 'RAsubAP.i90'
  end function subRArealDrealS
  elemental function subRArealDrealD(a,b) result(r)
    type(RArealD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RArealD)::r
    include 'RAsubAP.i90'
  end function subRArealDrealD
  elemental function subRArealDcomplexS(a,b) result(r)
    type(RArealD),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAP.i90'
  end function subRArealDcomplexS
  elemental function subRArealDcomplexD(a,b) result(r)
    type(RArealD),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAP.i90'
  end function subRArealDcomplexD
  elemental function subRAcomplexSinteger(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    integer,intent(in)::b
    type(RAcomplexS)::r
    include 'RAsubAP.i90'
  end function subRAcomplexSinteger
  elemental function subRAcomplexSrealS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RAcomplexS)::r
    include 'RAsubAP.i90'
  end function subRAcomplexSrealS
  elemental function subRAcomplexSrealD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAP.i90'
  end function subRAcomplexSrealD
  elemental function subRAcomplexScomplexS(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexS)::r
    include 'RAsubAP.i90'
  end function subRAcomplexScomplexS
  elemental function subRAcomplexScomplexD(a,b) result(r)
    type(RAcomplexS),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAP.i90'
  end function subRAcomplexScomplexD
  elemental function subRAcomplexDinteger(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    integer,intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAP.i90'
  end function subRAcomplexDinteger
  elemental function subRAcomplexDrealS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    real(kind=RAsKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAP.i90'
  end function subRAcomplexDrealS
  elemental function subRAcomplexDrealD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    real(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAP.i90'
  end function subRAcomplexDrealD
  elemental function subRAcomplexDcomplexS(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    complex(kind=RAsKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAP.i90'
  end function subRAcomplexDcomplexS
  elemental function subRAcomplexDcomplexD(a,b) result(r)
    type(RAcomplexD),intent(in)::a
    complex(kind=RAdKind),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubAP.i90'
  end function subRAcomplexDcomplexD
  elemental function subintegerRArealS(a,b) result(r)
    integer,intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAsubPA.i90'
  end function subintegerRArealS
  elemental function subintegerRArealD(a,b) result(r)
    integer,intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAsubPA.i90'
  end function subintegerRArealD
  elemental function subintegerRAcomplexS(a,b) result(r)
    integer,intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAsubPA.i90'
  end function subintegerRAcomplexS
  elemental function subintegerRAcomplexD(a,b) result(r)
    integer,intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubPA.i90'
  end function subintegerRAcomplexD
  elemental function subrealSRArealS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealS)::r
    include 'RAsubPA.i90'
  end function subrealSRArealS
  elemental function subrealSRArealD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAsubPA.i90'
  end function subrealSRArealD
  elemental function subrealSRAcomplexS(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAsubPA.i90'
  end function subrealSRAcomplexS
  elemental function subrealSRAcomplexD(a,b) result(r)
    real(kind=RAsKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubPA.i90'
  end function subrealSRAcomplexD
  elemental function subrealDRArealS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RArealD)::r
    include 'RAsubPA.i90'
  end function subrealDRArealS
  elemental function subrealDRArealD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RArealD)::r
    include 'RAsubPA.i90'
  end function subrealDRArealD
  elemental function subrealDRAcomplexS(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubPA.i90'
  end function subrealDRAcomplexS
  elemental function subrealDRAcomplexD(a,b) result(r)
    real(kind=RAdKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubPA.i90'
  end function subrealDRAcomplexD
  elemental function subcomplexSRArealS(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAsubPA.i90'
  end function subcomplexSRArealS
  elemental function subcomplexSRArealD(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubPA.i90'
  end function subcomplexSRArealD
  elemental function subcomplexSRAcomplexS(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexS)::r
    include 'RAsubPA.i90'
  end function subcomplexSRAcomplexS
  elemental function subcomplexSRAcomplexD(a,b) result(r)
    complex(kind=RAsKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubPA.i90'
  end function subcomplexSRAcomplexD
  elemental function subcomplexDRArealS(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RArealS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubPA.i90'
  end function subcomplexDRArealS
  elemental function subcomplexDRArealD(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RArealD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubPA.i90'
  end function subcomplexDRArealD
  elemental function subcomplexDRAcomplexS(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RAcomplexS),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubPA.i90'
  end function subcomplexDRAcomplexS
  elemental function subcomplexDRAcomplexD(a,b) result(r)
    complex(kind=RAdKind),intent(in)::a
    type(RAcomplexD),intent(in)::b
    type(RAcomplexD)::r
    include 'RAsubPA.i90'
  end function subcomplexDRAcomplexD
end module RAsub
