! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAsum
  use RAprec
  use RAtypes
  implicit none
  interface sum
    module procedure sumRArealS1
    module procedure sumRArealD1
    module procedure sumRAcomplexS1
    module procedure sumRAcomplexD1
    module procedure sumRArealS2
    module procedure sumRArealD2
    module procedure sumRAcomplexS2
    module procedure sumRAcomplexD2
    module procedure sumRArealS3
    module procedure sumRArealD3
    module procedure sumRAcomplexS3
    module procedure sumRAcomplexD3
    module procedure sumRArealS4
    module procedure sumRArealD4
    module procedure sumRAcomplexS4
    module procedure sumRAcomplexD4
    module procedure sumRArealS5
    module procedure sumRArealD5
    module procedure sumRAcomplexS5
    module procedure sumRAcomplexD5
    module procedure sumRArealS6
    module procedure sumRArealD6
    module procedure sumRAcomplexS6
    module procedure sumRAcomplexD6
    module procedure sumRArealS7
    module procedure sumRArealD7
    module procedure sumRAcomplexS7
    module procedure sumRAcomplexD7
  end interface sum
contains 
  function sumRArealS1(a) result(r)
    type(RArealS),intent(in)::a(:)
    type(RArealS)::r
    include 'RAsum.i90'
  end function sumRArealS1
  function sumRArealD1(a) result(r)
    type(RArealD),intent(in)::a(:)
    type(RArealD)::r
    include 'RAsum.i90'
  end function sumRArealD1
  function sumRAcomplexS1(a) result(r)
    type(RAcomplexS),intent(in)::a(:)
    type(RAcomplexS)::r
    include 'RAsum.i90'
  end function sumRAcomplexS1
  function sumRAcomplexD1(a) result(r)
    type(RAcomplexD),intent(in)::a(:)
    type(RAcomplexD)::r
    include 'RAsum.i90'
  end function sumRAcomplexD1
  function sumRArealS2(a) result(r)
    type(RArealS),intent(in)::a(:,:)
    type(RArealS)::r
    include 'RAsum.i90'
  end function sumRArealS2
  function sumRArealD2(a) result(r)
    type(RArealD),intent(in)::a(:,:)
    type(RArealD)::r
    include 'RAsum.i90'
  end function sumRArealD2
  function sumRAcomplexS2(a) result(r)
    type(RAcomplexS),intent(in)::a(:,:)
    type(RAcomplexS)::r
    include 'RAsum.i90'
  end function sumRAcomplexS2
  function sumRAcomplexD2(a) result(r)
    type(RAcomplexD),intent(in)::a(:,:)
    type(RAcomplexD)::r
    include 'RAsum.i90'
  end function sumRAcomplexD2
  function sumRArealS3(a) result(r)
    type(RArealS),intent(in)::a(:,:,:)
    type(RArealS)::r
    include 'RAsum.i90'
  end function sumRArealS3
  function sumRArealD3(a) result(r)
    type(RArealD),intent(in)::a(:,:,:)
    type(RArealD)::r
    include 'RAsum.i90'
  end function sumRArealD3
  function sumRAcomplexS3(a) result(r)
    type(RAcomplexS),intent(in)::a(:,:,:)
    type(RAcomplexS)::r
    include 'RAsum.i90'
  end function sumRAcomplexS3
  function sumRAcomplexD3(a) result(r)
    type(RAcomplexD),intent(in)::a(:,:,:)
    type(RAcomplexD)::r
    include 'RAsum.i90'
  end function sumRAcomplexD3
  function sumRArealS4(a) result(r)
    type(RArealS),intent(in)::a(:,:,:,:)
    type(RArealS)::r
    include 'RAsum.i90'
  end function sumRArealS4
  function sumRArealD4(a) result(r)
    type(RArealD),intent(in)::a(:,:,:,:)
    type(RArealD)::r
    include 'RAsum.i90'
  end function sumRArealD4
  function sumRAcomplexS4(a) result(r)
    type(RAcomplexS),intent(in)::a(:,:,:,:)
    type(RAcomplexS)::r
    include 'RAsum.i90'
  end function sumRAcomplexS4
  function sumRAcomplexD4(a) result(r)
    type(RAcomplexD),intent(in)::a(:,:,:,:)
    type(RAcomplexD)::r
    include 'RAsum.i90'
  end function sumRAcomplexD4
  function sumRArealS5(a) result(r)
    type(RArealS),intent(in)::a(:,:,:,:,:)
    type(RArealS)::r
    include 'RAsum.i90'
  end function sumRArealS5
  function sumRArealD5(a) result(r)
    type(RArealD),intent(in)::a(:,:,:,:,:)
    type(RArealD)::r
    include 'RAsum.i90'
  end function sumRArealD5
  function sumRAcomplexS5(a) result(r)
    type(RAcomplexS),intent(in)::a(:,:,:,:,:)
    type(RAcomplexS)::r
    include 'RAsum.i90'
  end function sumRAcomplexS5
  function sumRAcomplexD5(a) result(r)
    type(RAcomplexD),intent(in)::a(:,:,:,:,:)
    type(RAcomplexD)::r
    include 'RAsum.i90'
  end function sumRAcomplexD5
  function sumRArealS6(a) result(r)
    type(RArealS),intent(in)::a(:,:,:,:,:,:)
    type(RArealS)::r
    include 'RAsum.i90'
  end function sumRArealS6
  function sumRArealD6(a) result(r)
    type(RArealD),intent(in)::a(:,:,:,:,:,:)
    type(RArealD)::r
    include 'RAsum.i90'
  end function sumRArealD6
  function sumRAcomplexS6(a) result(r)
    type(RAcomplexS),intent(in)::a(:,:,:,:,:,:)
    type(RAcomplexS)::r
    include 'RAsum.i90'
  end function sumRAcomplexS6
  function sumRAcomplexD6(a) result(r)
    type(RAcomplexD),intent(in)::a(:,:,:,:,:,:)
    type(RAcomplexD)::r
    include 'RAsum.i90'
  end function sumRAcomplexD6
  function sumRArealS7(a) result(r)
    type(RArealS),intent(in)::a(:,:,:,:,:,:,:)
    type(RArealS)::r
    include 'RAsum.i90'
  end function sumRArealS7
  function sumRArealD7(a) result(r)
    type(RArealD),intent(in)::a(:,:,:,:,:,:,:)
    type(RArealD)::r
    include 'RAsum.i90'
  end function sumRArealD7
  function sumRAcomplexS7(a) result(r)
    type(RAcomplexS),intent(in)::a(:,:,:,:,:,:,:)
    type(RAcomplexS)::r
    include 'RAsum.i90'
  end function sumRAcomplexS7
  function sumRAcomplexD7(a) result(r)
    type(RAcomplexD),intent(in)::a(:,:,:,:,:,:,:)
    type(RAcomplexD)::r
    include 'RAsum.i90'
  end function sumRAcomplexD7
end module RAsum
