! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAtan
  use RAprec
  use RAtypes
  use RAdiv
  use RAsin
  use RAcos
  implicit none
  interface tan
    module procedure tanRArealS
    module procedure tanRArealD
    module procedure tanRAcomplexS
    module procedure tanRAcomplexD
  end interface tan
contains 
  elemental function tanRArealS(a) result(r)
    type(RArealS),intent(in)::a
    type(RArealS)::r
    include 'RAtan.i90'
  end function tanRArealS
  elemental function tanRArealD(a) result(r)
    type(RArealD),intent(in)::a
    type(RArealD)::r
    include 'RAtan.i90'
  end function tanRArealD
  elemental function tanRAcomplexS(a) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexS)::r
    include 'RAtan.i90'
  end function tanRAcomplexS
  elemental function tanRAcomplexD(a) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexD)::r
    include 'RAtan.i90'
  end function tanRAcomplexD
end module RAtan
