! This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
module RAuminus
  use RAprec
  use RAtypes
  implicit none
  interface operator(-)
    module procedure uminusRArealS
    module procedure uminusRArealD
    module procedure uminusRAcomplexS
    module procedure uminusRAcomplexD
  end interface 
contains 
  elemental function uminusRArealS(a) result(r)
    type(RArealS),intent(in)::a
    type(RArealS)::r
    include 'RAuminus.i90'
  end function uminusRArealS
  elemental function uminusRArealD(a) result(r)
    type(RArealD),intent(in)::a
    type(RArealD)::r
    include 'RAuminus.i90'
  end function uminusRArealD
  elemental function uminusRAcomplexS(a) result(r)
    type(RAcomplexS),intent(in)::a
    type(RAcomplexS)::r
    include 'RAuminus.i90'
  end function uminusRAcomplexS
  elemental function uminusRAcomplexD(a) result(r)
    type(RAcomplexD),intent(in)::a
    type(RAcomplexD)::r
    include 'RAuminus.i90'
  end function uminusRAcomplexD
end module RAuminus
